### PR TITLE
Fix misspelling of "outstanding"

### PR DESCRIPTION
**Pull request by dsedivec**

### CODE REVIEW

**Comment by mkcms** [comment]
Thanks.

**Comment by joaotavora** [comment]
@mkcms. Even trivial pull requests like this one should have proper commit messages and, most importantly
a "Copyright-paperwork-exempt: yes" line in the commit message.

**Comment by mkcms** [comment]
@joaotavora 
I **did** modify the commit message to include this information before merging. What else is missing?

**Comment by joaotavora** [comment]
> I did modify the commit message to include this information before merging. What else is missing?

Oh, sorry. Absolutely nothing :-) Never mind me then, I couldn't tell that you did that from the PR page. (perhaps you could add "Pushed with a tweak to the commit message" toyour "Thanks" message)

**Pull request merged**
