### PR TITLE
Make eglot-ignored-server-capabilites defcustom more user-friendly

### PR DESCRIPTION
**Pull request by mkcms**
* eglot.el (eglot-ignored-server-capabilites): Add list of possible
  choices to :type, along with a user-friendly description.

### CODE REVIEW

**Comment by joaotavora** [comment]
Oh this is very nice

**Comment by mkcms** [comment]
@joaotavora  I agree.
Any idea when you will have time to review/merge the other PRs? Thanks.

**Comment by joaotavora** [comment]
> Any idea when you will have time to review/merge the other PRs? Thanks.

hehehe, sorry for the gigantic delay.  I'm back to programming this week, with a very large backlog of stuff to fix, but yours is fairly top of the queue.  I also think it's important that some user testing goes into #65, and am glad that users like @whatacold have been doing that.

The main reason I haven't merged #65 yet is that I haven't found a good way of testing it reliably (I admit I didn't invest a lot of time too). Ultimately, adding automated tests to that PR would really give me the confidence to test some tweaks to your implementation without the fear of breaking something.  Do you think it is doable in `.travis.yml`?

**Comment by mkcms** [comment]
>  Do you think it is doable in `.travis.yml`?

Hmm, getting the server archive and setting the environment variable is definitely doable, other than that, I'm not sure what tests you have in mind. Just making a handshake with the server should be possible.

**Comment by joaotavora** [comment]
> Hmm, getting the server archive and setting the environment variable is definitely doable, other than that, I'm not sure what tests you have in mind. Just making a handshake with the server should be possible.

Oh, this would be a tremendous improvement already.

**Pull request merged**
