### PR TITLE
Fix version requirements

### PR DESCRIPTION
**Pull request by lbt**

### CODE REVIEW

**Comment by joaotavora** [comment]
I'd like to support 26.1.  26.3 doesn't add much code to 26.1  Can you do what I suggested in #562 and maybe we get project.el working in 26.1?  Thanks in advance.

**Comment by lbt** [comment]
project.el was moved to gnu ELPA and has required 26.3 from the first commit there.
See  http://elpa.gnu.org/packages/project.html

**Comment by joaotavora** [comment]
I know, I was the one who moved it :-) We need an Emacs bug to track if it can be specified to work with 26.1.  I'll open one tomorrow if you don't beat me to it.

In the meantime, can you test Emacs 26.1 + latest eglot by loading in the latest version of the `project.el` file?

**Comment by joaotavora** [comment]
I've done the testing, seems to have gone OK.  If you want to test, too, that'd be swell.

**Pull request closed without merging**
