### PR TITLE
Use temp directory as package-user-dir for installing ELPADEPS

### PR DESCRIPTION
**Pull request by muffinmad**
Avoid the installation of unneeded packages on `make eglot-check`.

### CODE REVIEW

**Comment by joaotavora** [comment]
Andrii Kolomoiets <notifications@github.com> writes:

> Avoid the installation of unneeded packages on make check.
>
> -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
>
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/joaotavora/eglot/pull/489
>
> Commit Summary
>
> * Use temp directory as package-user-dir for installing ELPADEPS

Not a bad idea.  Does it work OK in Travis?  It will be obsolete soon
when Eglot moves to core, but until then I don't see any reason why we
shouldn't.  So if it works and you're confident about it, push to
master.

João

**Comment by joaotavora** [comment]
Come to think of it, better hold this off for a while please. It's not working like it's supposed to in my tests.  Maybe I'm doing something silly.

**Comment by skangas** [comment]
This seems to have conflicts against master. Could you rebase on top of current master? Thanks!

**Comment by skangas** [comment]
I am seeing "This branch cannot be rebased due to conflicts" at the bottom, above the window where I am typing a comment. This was also the result I saw when I pulled the branch to my local repository and tried to rebase it.

**Comment by skangas** [comment]
@muffinmad Perhaps you are looking at your personal fork? Try this URL to see if you see the same as me there: https://github.com/joaotavora/eglot/pull/489

**Comment by muffinmad** [comment]
Well...
Знімок екрана 2022-01-14 о 10 35 35

**Comment by muffinmad** [comment]
Anyway, merged recent master now

**Comment by skangas** [comment]
> Well...

Hmm, this is weird. I am still seeing "This branch cannot be rebased due to conflicts"! The "Rebase and merge" button is greyed out, too. But that can't be right, as you just merged it.

Hmm...

Oh! So I can't "Rebase and merge" because there are merge commits on the branch. When I switch to "Squash and merge" or "Merge pull request", I correctly see "This branch has no conflicts with the base branch". So this was a cockpit error, sorry about that.

**Comment by joaotavora** [comment]
You can still rebase from the console, @skangas, with `git rebase --rebase-merges`.

**Comment by joaotavora** [comment]
Or, becasue it is so simple, I'd just squash and merge.  I'll do it myself...

**Comment by skangas** [comment]
Thanks.

**Comment by skangas** [comment]
> You can still rebase from the console, @skangas, with `git rebase --rebase-merges`.

Yup, but that's more work than clicking. ;-)

**Pull request merged**
