### PR TITLE
Rebase "Fix #76: Enable eglot in files referenced by xrefs" on current master

### LINKED ISSUE #76: Enabling eglot in files outside current project after following xrefs
When I find a definition outside current project, eglot is either not enabled or enabled, but using a different server. I'd like to have it enabled and using the same server where it came from, unless I explicitly started it with `eglot` or there was already a server managing this buffer started with `eglot-ensure`, but not in a transient project.

### PR DESCRIPTION
**Pull request by cmm**
* eglot.el (eglot-lsp-server): New slot external-roots.
(eglot--probing-projects): New defvar.
(eglot--project-try-external-roots): New helper.
(eglot--current-server): Bind eglot--project-projects to t
(eglot--xref-make): Push xref's file directory into server's
external-roots.
(project-find-functions): Add eglot--project-try-external-roots

### CODE REVIEW

**Comment by cmm** [comment]
@joaotavora and with today's master (after 40bba97b0ab81ea3e70884b754d59a2e5af5e5f5) the needed changes in eglot itself are reduced to just recording "external" xref locations -- the rest (extending `project-find-functions` with something that looks at `eglot-lsp-context`) can be done by the user.

**Comment by joaotavora** [comment]
Cool so you're saying those changes of of #689 _also_ simplify this?  That's unintended and pretty cool! But can you explain how?

**Comment by joaotavora** [comment]
I think I understand how (but please do try to explain yourself since I may be wrong).  Whatever that user-defined `project-find-functions` element is, maybe we can bundle it with `eglot.el` for convenience...

**Comment by cmm** [comment]
sure!  this is what I do now:
```
(defun cmm/project-try-xref-locations (dir)
  "Probe `eglot--servers-by-project' for a server handling DIR."
  (when eglot-lsp-context
    (catch 'found
      (maphash (lambda (project servers)
                 (dolist (server servers)
                   (when (member (expand-file-name dir)
                                 (eglot--xref-locations server))
                     (throw 'found project))))
               eglot--servers-by-project))))
(add-hook 'project-find-functions #'cmm/project-try-xref-locations t)
```
(as you can see it still has to look at eglot's innards, so bundling something similar would definitely be helpful)

**Comment by joaotavora** [comment]
>  similar would definitely be helpful

Yes, it would, indeed.  Probing innards from config files isn't desired.

I still want to re-understand exactly how this from the moment that `M-.` happens to the result.  But that's on me to read the code (unless you want to lay out an outline of who calls who :-) to make it easy for me)

**Comment by cmm** [comment]
>who calls who

user presses `M-.`, things happen and `eglot--lsp-xrefs-for-method` is called (I'm unclear on how exactly), and it formats the matches using `eglot--xref-make-match`.  the change in this PR causes `eglot--xref-make-match` to record the match's file's directory in the current server instance.

**Comment by cmm** [comment]
also see #695 for a more direct approach that does not need to involve `project-find-functions`

**Pull request closed without merging**
