### PR TITLE
Fix #863: Use jdtls for Eclipse JDT

### LINKED ISSUE #863: Feature request, help wanted: Integrate new Eclipse JDT  Python script and remove lots of Eclipse JDT code
In https://github.com/eclipse/eclipse.jdt.ls/issues/748, it seems the Eclipse JDT project finally added a Python Script that can start a Java process setting up the JDT server with sane defaults.  

It would be great if this could give rise to an entry in `eglot-server-programs` and allow this deletion:
```diff
diff --git a/eglot.el b/eglot.el
index 7bff005..4d2f2b7 100644
--- a/eglot.el
+++ b/eglot.el
@@ -3013,100 +3013,6 @@ If NOERROR, return predicate, else erroring function."
   (when (eq ?! (aref arg 1)) (aset arg 1 ?^))
   `(,self () (re-search-forward ,(concat "\\=" arg)) (,next)))
 
-
-;;; eclipse-jdt-specific
-;;;
-(defclass eglot-eclipse-jdt (eglot-lsp-server) ()
-  :documentation "Eclipse's Java Development Tools Language Server.")
-
-(cl-defmethod eglot-initialization-options ((server eglot-eclipse-jdt))
-  "Passes through required jdt initialization options."
-  `(:workspaceFolders
-    [,@(cl-delete-duplicates
-        (mapcar #'eglot--path-to-uri
-                (let* ((root (project-root (eglot--project server))))
-                  (cons root
-                        (mapcar
-                         #'file-name-directory
-                         (append
-                          (file-expand-wildcards (concat root "*/pom.xml"))
-                          (file-expand-wildcards (concat root "*/build.gradle"))
-                          (file-expand-wildcards (concat root "*/.project")))))))
-        :test #'string=)]
-    ,@(if-let ((home (or (getenv "JAVA_HOME")
-                         (ignore-errors
-                           (expand-file-name
-                            ".."
-                            (file-name-directory
-                             (file-chase-links (executable-find "javac"))))))))
-          `(:settings (:java (:home ,home)))
-        (ignore (eglot--warn "JAVA_HOME env var not set")))))
-
-(defun eglot--eclipse-jdt-contact (interactive)
-  "Return a contact for connecting to eclipse.jdt.ls server, as a cons cell.
-If INTERACTIVE, prompt user for details."
-  (cl-labels
-      ((is-the-jar
-        (path)
-        (and (string-match-p
-              "org\\.eclipse\\.equinox\\.launcher_.*\\.jar$"
-              (file-name-nondirectory path))
-             (file-exists-p path))))
-    (let* ((classpath (or (getenv "CLASSPATH") path-separator))
-           (cp-jar (cl-find-if #'is-the-jar (split-string classpath path-separator)))
-           (jar cp-jar)
-           (dir
-            (cond
-             (jar (file-name-as-directory
-                   (expand-file-name ".." (file-name-directory jar))))
-             (interactive
-              (expand-file-name
-               (read-directory-name
-                (concat "Path to eclipse.jdt.ls directory (could not"
-                        " find it in CLASSPATH): ")
-                nil nil t)))
-             (t (error "Could not find eclipse.jdt.ls jar in CLASSPATH"))))
-           (repodir
-            (concat dir
-                    "org.eclipse.jdt.ls.product/target/repository/"))
-           (repodir (if (file-directory-p repodir) repodir dir))
-           (config
-            (concat
-             repodir
-             (cond
-              ((string= system-type "darwin") "config_mac")
-              ((string= system-type "windows-nt") "config_win")
-              (t "config_linux"))))
-           (workspace
-            (expand-file-name (md5 (project-root (eglot--current-project)))
-                              (locate-user-emacs-file
-                               "eglot-eclipse-jdt-cache"))))
-      (unless jar
-        (setq jar
-              (cl-find-if #'is-the-jar
-                          (directory-files (concat repodir "plugins") t))))
-      (unless (and jar (file-exists-p jar) (file-directory-p config))
-        (error "Could not find required eclipse.jdt.ls files (build required?)"))
-      (when (and interactive (not cp-jar)
-                 (y-or-n-p (concat "Add path to the server program "
-                                   "to CLASSPATH environment variable?")))
-        (setenv "CLASSPATH" (concat (getenv "CLASSPATH") path-separator jar)))
-      (unless (file-directory-p workspace)
-        (make-directory workspace t))
-      (cons 'eglot-eclipse-jdt
-            (list (executable-find "java")
-                  "-Declipse.application=org.eclipse.jdt.ls.core.id1"
-                  "-Dosgi.bundles.defaultStartLevel=4"
-                  "-Declipse.product=org.eclipse.jdt.ls.core.product"
-                  "-jar" jar
-                  "-configuration" config
-                  "-data" workspace)))))
-
-(cl-defmethod eglot-execute-command
-  ((_server eglot-eclipse-jdt) (_cmd (eql java.apply.workspaceEdit)) arguments)
-  "Eclipse JDT breaks spec and replies with edits as arguments."
-  (mapc #'eglot--apply-workspace-edit arguments))
-
 
 ;;; Obsolete
 ;;;
```

CC: @astoff , @skangas if you know someone who's using this server please tag them here.  If anyone is willing to experiment with this, it'd be most welcome

### PR DESCRIPTION
**Pull request by manuel-uberti**
A couple of questions:
- Do we need to specify somewhere the Python version required for `jdtls` to run as expected? (See #863)
- This removes plenty of code and I only tested it with a single Java file. Is there any chance someone with bigger projects in his hands can give this a try?

### CODE REVIEW

**Comment by joaotavora** [comment]
Hi @manuel-uberti.  Thank you very much for this.

I think the best course of action is to merge this and then prepare an annoucement post on the discussion board where you explain the change, and in that board paste back the code that was removed along with the necessary to `eglot-server-programs` to reactivate it.

This should provide some feedback.

**Comment by manuel-uberti** [comment]
Sure thing. I can create the post on the discussion board after the merge. As you prefer. :)

**Comment by joaotavora** [comment]
> I can create the post on the discussion board after the merge

Great! Can you type up a draft of this post here in the PR and then we can iterate it?  I'd like it to contain a very short introduction explaining why this change was made, which is dramatically reducing the amount of server/language-specific code in out language agnostic LSP client, along with two main elements:

1. Simple instructions on how to use the new `jdtls` Python script, minimum Python version, how to set up `PATH` (or emacs's `exec-path`), links to JDT's documentation on that script's interface.
2. Simple instructions on how to place the removed code in one's Emacs initialization file (`.emacs` or `~/.emacs.d/init.el`) and gain back the previous interface.

**Comment by manuel-uberti** [comment]
I can try.

# Integrate new Eclipse JDT Python script

https://github.com/joaotavora/eglot/pull/864 changes how Eglot interacts with Eclipse JDT according to [Add Package Manager Friendly Start Up Script](https://github.com/eclipse/eclipse.jdt.ls/pull/2005). Mainly, there is a new `jdtls` Python script that sets up Eclipse JDT with the default options Eglot needs to work with it.

## Install jdtls

In order for `jdtls` to work, you will need Python 3.9 or a later version (see: https://github.com/joaotavora/eglot/issues/863#issuecomment-1061590285).

Assuming you have the correct Python version, starting from Eclipse JDT 1.9.0 `jdtls` is available in the `bin` directory of the released archive you can find at http://download.eclipse.org/jdtls/milestones/.

For Eglot to use `jdtls`, make sure it is available in your `$PATH`. For instance:

```shell
$ ln -s /home/user/jdt/bin/jdtls /user/local/bin/jdtls
$ chmod +x /user/local/bin/jdtls
```

In your Java files, now you can use <kbd>M-x eglot</kbd> and everything should be working as expected.

## Restore the previous interface

If for some reason you cannot make `jdtls` work on your system (e.g., you do not have access to a recent Python version), you can edit `eglot.el` and restore the code https://github.com/joaotavora/eglot/pull/864 removed.

Specifically, you have to change `eglot-server-programs` to use the old code, thus replacing `(java-mode . ("jdtls"))` with `(java-mode . eglot--eclipse-jdt-contact)`, and add the following code somewhere above the `;;; Obsolete` comment:

```emacs-lisp
;;; eclipse-jdt-specific
;;;
(defclass eglot-eclipse-jdt (eglot-lsp-server) ()
  :documentation "Eclipse's Java Development Tools Language Server.")

(cl-defmethod eglot-initialization-options ((server eglot-eclipse-jdt))
  "Passes through required jdt initialization options."
  `(:workspaceFolders
    [,@(cl-delete-duplicates
        (mapcar #'eglot--path-to-uri
                (let* ((root (project-root (eglot--project server))))
                  (cons root
                        (mapcar
                         #'file-name-directory
                         (append
                          (file-expand-wildcards (concat root "*/pom.xml"))
                          (file-expand-wildcards (concat root "*/build.gradle"))
                          (file-expand-wildcards (concat root "*/.project")))))))
        :test #'string=)]
    ,@(if-let ((home (or (getenv "JAVA_HOME")
                         (ignore-errors
                           (expand-file-name
                            ".."
                            (file-name-directory
                             (file-chase-links (executable-find "javac"))))))))
          `(:settings (:java (:home ,home)))
        (ignore (eglot--warn "JAVA_HOME env var not set")))))

(defun eglot--eclipse-jdt-contact (interactive)
  "Return a contact for connecting to eclipse.jdt.ls server, as a cons cell.
If INTERACTIVE, prompt user for details."
  (cl-labels
      ((is-the-jar
        (path)
        (and (string-match-p
              "org\\.eclipse\\.equinox\\.launcher_.*\\.jar$"
              (file-name-nondirectory path))
             (file-exists-p path))))
    (let* ((classpath (or (getenv "CLASSPATH") path-separator))
           (cp-jar (cl-find-if #'is-the-jar (split-string classpath path-separator)))
           (jar cp-jar)
           (dir
            (cond
             (jar (file-name-as-directory
                   (expand-file-name ".." (file-name-directory jar))))
             (interactive
              (expand-file-name
               (read-directory-name
                (concat "Path to eclipse.jdt.ls directory (could not"
                        " find it in CLASSPATH): ")
                nil nil t)))
             (t (error "Could not find eclipse.jdt.ls jar in CLASSPATH"))))
           (repodir
            (concat dir
                    "org.eclipse.jdt.ls.product/target/repository/"))
           (repodir (if (file-directory-p repodir) repodir dir))
           (config
            (concat
             repodir
             (cond
              ((string= system-type "darwin") "config_mac")
              ((string= system-type "windows-nt") "config_win")
              (t "config_linux"))))
           (workspace
            (expand-file-name (md5 (project-root (eglot--current-project)))
                              (locate-user-emacs-file
                               "eglot-eclipse-jdt-cache"))))
      (unless jar
        (setq jar
              (cl-find-if #'is-the-jar
                          (directory-files (concat repodir "plugins") t))))
      (unless (and jar (file-exists-p jar) (file-directory-p config))
        (error "Could not find required eclipse.jdt.ls files (build required?)"))
      (when (and interactive (not cp-jar)
                 (y-or-n-p (concat "Add path to the server program "
                                   "to CLASSPATH environment variable?")))
        (setenv "CLASSPATH" (concat (getenv "CLASSPATH") path-separator jar)))
      (unless (file-directory-p workspace)
        (make-directory workspace t))
      (cons 'eglot-eclipse-jdt
            (list (executable-find "java")
                  "-Declipse.application=org.eclipse.jdt.ls.core.id1"
                  "-Dosgi.bundles.defaultStartLevel=4"
                  "-Declipse.product=org.eclipse.jdt.ls.core.product"
                  "-jar" jar
                  "-configuration" config
                  "-data" workspace)))))

(cl-defmethod eglot-execute-command
  ((_server eglot-eclipse-jdt) (_cmd (eql java.apply.workspaceEdit)) arguments)
  "Eclipse JDT breaks spec and replies with edits as arguments."
  (mapc #'eglot--apply-workspace-edit arguments))
```

**Comment by joaotavora** [comment]
This looks very good. I've made some edits.  Have another look.

**Comment by manuel-uberti** [comment]
Great, thanks, I think we are all set here.

**Comment by joaotavora** [comment]
Cool! Merged this.  Go ahead and make the post.

**Comment by manuel-uberti** [comment]
Done: https://github.com/joaotavora/eglot/discussions/868

**Comment by joaotavora** [comment]
This broke the automated tests.  I will look into it.

**Comment by manuel-uberti** [comment]
Sorry about that. Thank you for having taken care of it.

**Pull request merged**
