### PR TITLE
Add enh-ruby-mode

### PR DESCRIPTION
**Pull request by filalex77**

### CODE REVIEW

**Comment by joaotavora** [comment]
Thanks for the suggestion, but wouldn't it make for sense for `enh-ruby-mode` to derive from `ruby-mode`?

**Comment by filalex77** [comment]
@joaotavora Yes, @PuercoPop is right: `enh-ruby-mode` is a standalone mode which aims to replace `ruby-mode` with actual AST parsing.

**Comment by joaotavora** [comment]
@PuercoPop @filalex77 , I know. But would there be an actual disadvantage if you make `enh-ruby-mode` inherit from `ruby-mode`? Because there would be an advantage, which is: it would work with eglot.

**Comment by PuercoPop** [comment]
>  But would there be an actual disadvantage if you make enh-ruby-mode inherit from ruby-mode?

I don't know, I use ruby-mode myself. But the author of enh-ruby chose not to and it seems to be reasonable popular.

>  Because there would be an advantage, which is: it would work with eglot.

I'm unclear as to what makes the situation of enh-ruby different from js2-mode. Seems like adding the entry to `eglot-server-programs` is the path of least resistance that delivers best user experience. Btw `rjsx-mode` already derives from js2-mode, should that entry be removed?

https://github.com/joaotavora/eglot/blob/master/eglot.el#L85

**Comment by PuercoPop** [comment]
> But popularity is not really an objective measure, is it?

Indeed, that is why I was vague – 'reasonably popular' – instead asserting w/o any data to back me up what is my impression, that enh-ruby is the most popular of the two. It is the default in the Ruby layer of spacemacs f/e. Also popularity doesn't mean better either, I have to use Ruby at $work and I'm happy with ruby-mode so this issue doesn't affect me personally. 

> My money is on most likely he didn't consider the advantages/disadvantages.

From skimming through the code, there is a lot of code repeating the same syntax entries that ruby-mode.el so I'm inclined to agree with you. However, what is the one-liner that you are more confident won't break anything, making enhanced-ruby-mode inherit from ruby-mode or merging this PR? 

I agree with you that the ideal way to solve this issue would be to modify enhanced-ruby-mode, but I'm not understanding what (software) principle you are defending here. This seems like a one-liner that would make eglot easier to use out of the box for some ruby users.

> Indeed thanks for bringing this to my attention.

The outcome was the opposite of what I intended but no one can say you aren't being coherent :grin:

Anyway just my 2¢ and thanks for eglot. It improved my JS experience significantly.

**Comment by filalex77** [comment]
Closing due to lack of rationale.

**Pull request closed without merging**
