### PR TITLE
Support futhark lsp

### PR DESCRIPTION
**Pull request by athas**
* eglot.el (eglot-server-programs): support futhark lsp.
* README.md:
* NEWS.md: Update for above changes.

### CODE REVIEW

**Comment by joaotavora** [comment]
Thanks.  I will try to merge this soon, but if you mimic exactly the commit message format adopted by one of the more recent additions to the out-of-box list, it's as easy as pressing the big green button for me :-)

**Comment by athas** [comment]
Alright, I'll try to mimic 86221e05c0909645761dc72e917888b8a782eeab.

**Comment by athas** [comment]
I imitated it as much as I could, but there was of course no GitHub discussion thread I could link to.

**Comment by joaotavora** [comment]
Thanks.  There were a few bits missing, including the important `Copyright-paperwork-exempt: yes`.  But it's ok, no point in doing another iteration. I tweaked and merged it.

**Comment by athas** [comment]
Thanks!  Eglot is really nice.  I never expected LSP support in Emacs could be done this smoothly.  Major kudos for implementing it in a single easily navigable file.

**Pull request merged**
