### PR TITLE
Add a variable to withhold the init req process id

### PR DESCRIPTION
**Pull request by spearalot**
I do not know if this is useful, but it allows me to use docker to run my language servers e,g:
(web-mode . ("/usr/bin/flatpak-spawn" "--host" "docker" "exec" "-i" "dev-image" "typescript-language-server" "--stdio"))

### CODE REVIEW

**Comment by joaotavora** [comment]
I guess this makes sense, but can you make this a defvar instead?  A defcustom is normally global, and this seems like the kind of thing you would put in a major mode hook.

**Comment by spearalot** [comment]
That makes sense. I've replaced the custom with a var.

**Comment by joaotavora** [comment]
Thanks, but the `defvar` form has now become invalid.  You can't have the `type` there, I think.  It would also be nice to document, very briefly, this variable in the README file, in the appropriate section.

**Comment by skangas** [comment]
@spearalot Any updates here? Thanks!

**Comment by skangas** [comment]
I fixed it up and merged it to master.

@spearalot Thanks for your contribution!

**Pull request merged**
