### PR TITLE
Update Imenu asynchronously.

### LINKED ISSUE #212: Blocking eglot-imenu
Currently `eglot-imenu` is blocking and waits using the default timeout. However, it's called in places where blocking calls are extremely undesirable, e.g. in the idle timer used by `which-function-mode`. This makes buffers unusable if `which-function-mode` is enabled and the server doesn't react immediately. I'd suggest to make `eglot-imenu` asynchronous, i.e. it should return a cached result and fire off an asynchronous update in the background. That means the results might be a bit stale, but that's still better than blocking input.

### PR DESCRIPTION
**Pull request by phst**
The Imenu entries must be available instantaneously because they are used in
‘find-file-hook’ and the timer used by ‘which-function’.

Fixes #212

* eglot.el (eglot--imenu-entries): New defvar.
(eglot--update-imenu): New defun.
(eglot-imenu): Update index asynchronously.

### CODE REVIEW

**Comment by joaotavora** [comment]
Thanks.  Had a very very cursory look. Doesn't look bad, have to understand edge cases.  Is too much to ask for a test?

**Comment by phst** [comment]
> Is too much to ask for a test?

Definitely not, but it'll take a bit

**Comment by joaotavora** [comment]
@phst , I'm having a look at Eglot's imenu code once again in #303. That PR is mostly orthogonal to this one, but it made me have a look at your code again, and I think there might be a problem: what happens, in your version, on the very first `M-x imenu` call in a buffer? Don't we want blocking behaviour there?

**Comment by joaotavora** [comment]
As I said in #212, I've had a better look at this and I don't think Eglot should be responsible for caching this kind of thing.  The Imenu operation can be expensive for a lot of other reasons (not just Eglot-specific reasons).

**Pull request closed without merging**
