### PR TITLE
add option eglot-highlight-symbol-at-point-p

### PR DESCRIPTION
**Pull request by brotzeit**

### CODE REVIEW

**Comment by joaotavora** [comment]
I fear we'll have to add one such option for everything that this or that user wants to disable. How about this instead?

```diff
diff --git a/eglot.el b/eglot.el
index 6193b93..ce666f8 100644
--- a/eglot.el
+++ b/eglot.el
@@ -816,16 +816,23 @@ If optional MARKER, return a marker instead"
       (ignore-errors (funcall mode))
       (insert string) (font-lock-ensure) (buffer-string))))
 
+(defcustom eglot-ignored-server-capabilites nil
+  "LSP server capabilities that Eglot could use, but won't."
+  :type '(list symbol))
+
 (defun eglot--server-capable (&rest feats)
   "Determine if current server is capable of FEATS."
-  (cl-loop for caps = (eglot--capabilities (eglot--current-server-or-lose))
-           then (cadr probe)
-           for feat in feats
-           for probe = (plist-member caps feat)
-           if (not probe) do (cl-return nil)
-           if (eq (cadr probe) t) do (cl-return t)
-           if (eq (cadr probe) :json-false) do (cl-return nil)
-           finally (cl-return (or probe t))))
+  (unless (cl-some (lambda (feat)
+                     (memq feat eglot-ignored-server-capabilites))
+                   feats)
+    (cl-loop for caps = (eglot--capabilities (eglot--current-server-or-lose))
+             then (cadr probe)
+             for feat in feats
+             for probe = (plist-member caps feat)
+             if (not probe) do (cl-return nil)
+             if (eq (cadr probe) t) do (cl-return t)
+             if (eq (cadr probe) :json-false) do (cl-return nil)
+             finally (cl-return (or probe t)))))
 
 (defun eglot--range-region (range &optional markers)
   "Return region (BEG . END) that represents LSP RANGE.
```

**Comment by brotzeit** [comment]
I don't understand these changes. How can I add a feature to `eglot-ignored-server-capabilites` ? Why don't you run the loop if a feature is in that list ? I think you should add a small note to the docstring of the `defcustom`.

**Comment by joaotavora** [comment]
@brotzeit, to do what you want in this case, either customize the variable with the defcustom interface and add in the symbol `:documentHighlightProvider`

Or add in your `.emacs`

```lisp
(add-to-list 'eglot-server-ignored-capabilities :documentHighlightProvider)
```

**Comment by joaotavora** [comment]
> Why don't you run the loop if a feature is in that list 

Because, if a feature is in that list, I want `eglot--server-capable` to return nil. I should change the name of `eglot--server-capable` to reflect that it only returns non-nil if the server *is* capable *and* Eglot is willing to accept that capability, but that's an implementation detail (notice the double "--" in `eglot--server-capable`).

**Comment by brotzeit** [comment]
Thanks for the explanation. And also thanks for the package!

**Pull request closed without merging**
