### PR TITLE
Per #687: provide context for finer project-find-functions

### PR DESCRIPTION
**Pull request by joaotavora**
* eglot.el (eglot--guess-contact): Use eglot--current-project.
(eglot): Adjust docstring.
(eglot-lsp-context): New variable.vc dq
(eglot--current-project): New helper.
(eglot--maybe-activate-editing-mode, eglot--eclipse-jdt-contact):
Use eglot--current-project.

### CODE REVIEW

**Comment by dgutov** [comment]
What I suggested is to have a separate hook (like `eglot-root-functions`) or a variable that the user is supposed to set to a list of strings (relative directory files names), not a dynamic boolean var.

This should be good enough to experiment, though.

**Comment by joaotavora** [comment]
> What I suggested is to have a separate hook (like eglot-root-functions) or a variable that the user is supposed to set to a list of strings (relative directory files names), not a dynamic boolean var.

I didn't understand your suggestion, sorry. That would work, but seems like someting that `project.el` is already doing: finding base directories according to certain rules.  The dynamic variable is a generalized boolean for now (nil or non-nil), but that non-nil can be set to something "richer" later on.  We can also institute some simple criteria like the presence of an empty `.eglot-root` file and have `eglot--current-project` respect it.  The base idea of `eglot.el` is to `M-x eglot` and little to no `.emacs` customization.

**Comment by dgutov** [comment]
The idea is to affect what Eglot does (for technical reasons) but not affect what `project-find-file` does (for example).

Using a different hook is a cleaner way to separate responsibilities.

And "finding base directories according to certain rules" is what `locate-dominating-file` does as well.

**Comment by joaotavora** [comment]
> And "finding base directories according to certain rules" is what locate-dominating-file does as well.

That just finds a given file though, right? Not really a "rule" system.

> Using a different hook is a cleaner way to separate responsibilities.

Cleaner is always a subjective view.  

Let me try to explain why I don't agree:  Eglot's philosophy is also to be as sparse as possible in terms of customization constructs, especially when these can be conceivably be found in other parts of Emacs.  I see #687  's use case (yet to be fleshed out) as a exception to the fact that `project-find-functions` whatever they are, match the LSP root most of the time, say, 98%.  So my solution provides a smaller dial to fix the 2%. The price is that the `p-f-f` function written by those 2% of users will have an extra `(if eglot-lsp-context...`. Is that "unclean"? Maybe, if the split was say 50-50% or worse.  Then maybe your idea would be better.  But as it stands, its price is a new customization entry point that is useless for 98%.

**Comment by dgutov** [comment]
When a customization is necessary for Eglot and is needed in Eglot only, its place is certainly there.

I'm not sure the solution here is a customization, though, and not a hardcoded set of rules.

**Comment by joaotavora** [comment]
> When a customization is necessary for Eglot and is needed in Eglot only, its place is certainly there.

You mean "customization variable/endpoint" right? (customization itself lives in the user's files). Well, can't see how to disagree with that. I'm not proposing any new customization variables, though, Eglot or elsewhere.

> I'm not sure the solution here is a customization, though, and not a hardcoded set of rules.

What do you mean? If it's looking for `.eglot-root` or something, I think that makes sense.

**Comment by dgutov** [comment]
> You mean "customization variable/endpoint" right?

A customization event. The action of someone customizing something.

> What do you mean? If it's looking for .eglot-root or something, I think that makes sense.

I'm thinking of how VS Code probably doesn't require the user to create magical `.vs-code-root` in certain project subdirectories. Could be wrong, though.

**Comment by joaotavora** [comment]
> A customization event. The action of someone customizing something.

In that case, that event takes place in the user's configs.  Not Eglot or anywhere else.  So the thing I can agree with is "when a configuration is needed for LSP only, and a new endpoint is needed, that endpoint should be named `eglot--foo`".  I'm trying to avoid creating a new endpoint, is all.

> I'm thinking of how VS Code probably doesn't require the user to create magical .vs-code-root in certain project subdirectories. Could be wrong, though.

Isn't that knowledge in the LSP server, and not the client?  Maybe VScode has server-specific hints? Many server do violate the abstraction in part, and require VScode-specific extensions, but there's nothing Eglot can do about that.  Any piece of server-specific information (conversely, any piece of client-specific information) that lives in the client (conversely, server) is a bad idea simply because it doesn't scale, isn't maintainabl, etc: in short the problems LSP was built to solve.

Indeed another natural solution to this problem (that both of us seem to be overestimating) is for this to make it into the protocol somehow. 

And again, Emacs happens to already have an historical collection of language specific facilities called major modes.  If some major mode wants to prefer a server and inform Eglot about special ways to find the project root for it, I have nothing against, quite the contrary.  I do estimate "preferring a server" to be quite common but "special project root" to be less common.

**Comment by dgutov** [comment]
>  So the thing I can agree with is "when a configuration is needed for LSP only, and a new endpoint is needed, that endpoint should be named eglot--foo". I'm trying to avoid creating a new endpoint, is all.

You're saying something like "a new endpoint is not needed because it's not needed".

> Isn't that knowledge in the LSP server, and not the client? Maybe VScode has server-specific hints? Many server do violate the abstraction in part, and require VScode-specific extensions, but there's nothing Eglot can do about that. Any piece of server-specific information (conversely, any piece of client-specific information) that lives in the client (conversely, server) is a bad idea simply because it doesn't scale, isn't maintainabl, etc: in short the problems LSP was built to solve.

That's nothing new, though. And where it's not too hard to do on the part of Eglot, and relatively difficult for the user to figure out, either Eglot steps up, or the feature ends up effectively unsupported.

> Indeed another natural solution to this problem (that both of us seem to be overestimating) is for this to make it into the protocol somehow.

Sure, but that's not an immediate solution. It could replace the immediate solution sometime down the line.

> If some major mode wants to prefer a server and inform Eglot about special ways to find the project root for it, I have nothing against, quite the contrary.

And if some do, that would happen through some Eglot-specific variable or several.

**Pull request merged**
