### PR TITLE
Fix a typo in the docstring of eglot-shutdown

### PR DESCRIPTION
**Pull request by xuchunyang**

### CODE REVIEW

**Comment by joaotavora** [comment]
@xuchunyang , I'm going to merge this, but you should probably start your FSF copyright assignment process if you wish to continue contributing to Eglot.  This is because the 15-line rule-of-thumb copyright exemption is cumulative.  I'm not sure how many lines you're up to already :-)

**Comment by xuchunyang** [comment]
@joaotavora I assigned the copyright assignment for the emacs project a few years ago. However, I never needed it. Do you know if is there a way to confirm if my copyright assignment is ok?https://www.gnu.org/prep/maintain/html_node/Copyright-Papers.html suggests FSF clerks can check this. But I still don't know who I can contact for help about this.

**Comment by joaotavora** [comment]
> @joaotavora I assigned the copyright assignment for the emacs project a few years ago. However, I never needed it.

Great. Perhaps you even told me this already and I forgot.  I think you should just mail assign@gnu.org asking if your copyright assignment is on file.

**Comment by xuchunyang** [comment]
I've sent an email. Thanks for the help.

**Comment by xuchunyang** [comment]
I received a reply, my copyright assignment is still on file and I am OK to contribute.

Sorry for the noise.

**Pull request closed without merging**
