### PR TITLE
Support server-initiated workspace/applyEdit

### PR DESCRIPTION
**Pull request by eschulte**
My reading of the [LSP CodeAction Request](https://microsoft.github.io/language-server-protocol/specification#textDocument_codeAction) specification is that there are two ways that an LSP server could respond to a CodeAction Request:
1. It may send back a list of Commands which the client then selects, then the server responds to the selection by notifying the client with a workspace/applyEdit to enact the command, or
2. The server may directly send back a list of edit actions which the user selects and applies without another round trip.

Currently Eglot only supports (2).  This patch adds support for (1), which according to the Spec cited above is still useful in some cases "server providers should be aware that if the code action is expensive to compute or the edits are huge it might still be beneficial if the result is simply a command and the actual edit is only computed when needed."

So I guess there are two parts to this:
1. Do you agree supporting both of these models of CodeAction is useful and something that you'd like Eglot to support,
2. If so, does this patch look like an acceptable implementation (I've confirmed it works with one in-development LSP server)?

Thanks!

### CODE REVIEW

**Comment by joaotavora** [comment]
> Currently Eglot only supports (2). This patch adds support for (1), 

I'm quite confused.  I thought it was the other way around.  Reading `eglot-code-action` seems to show that.  But whatever happens I'm interested in supporting both cases, yes.

Do you have an Emacs copyright assignment?

**Comment by joaotavora** [comment]
> I'm quite confused. I thought it was the other way around. 

Not only that, but you'll notice that for the custom `eglot-eclipse-jdt` server, there is code that does support direct application of edits.

And beyond that, the confusion intensifies, in your patch you propose a *notification* handler for `workspace/applyEdit`, but that is not specified to be a notification at all!

**Comment by eschulte** [comment]
Oh, you're totally right that this should be a request from the server to Eglot, not a notification.  I'll have to sort that out on my end.  Sorry for the noise!

FWIW: I do have an Emacs copyright assignment.  Long ago I was a big Org-mode contributor, and a little more recently my https://github.com/eschulte/emacs-web-server is also FSF assigned.

Thanks

**Comment by joaotavora** [comment]
> request from the server to Eglot, not a notification

I don't mean to add to the confusion: those kinds of this do exist, but are you 100% they exist for `workspace/applyEdit`? 

> FWIW: I do have an Emacs copyright assignment. Long ago I was a big Org-mode contributor, and a little more recently my https://github.com/eschulte/emacs-web-server is also FSF assigned.

Yes, I think I recognized your name for something I used here or there (though I'm not _that_ much of an Org user).  Anyway, it's great and I'm happy to have your contributions to Eglot.

**Pull request closed without merging**
