### PR TITLE
Close #44: Cleanup kill-buffer-hook properly

### LINKED ISSUE #44: Problems changing major modes of eglot-managed buffers
Steps to reproduce:

1. Visit a C header (in `c-mode`)
2. `M-x eglot`
3. `M-x c++-mode`
4. Try to kill current buffer
5. Buffer is not killed, error is signaled:

`Debugger entered--Lisp error: (jsonrpc-error "No current JSON-RPC connection" (jsonrpc-error-code . 32603) (jsonrpc-error-message . "No current JSON-RPC connection"))`

This is because `kill-buffer-hook` (which calls `eglot--signal-textDocument/didClose`) is a permanent local variable, which means it isn't cleared after changing major modes.

### PR DESCRIPTION
**Pull request by mkcms**
This is a simple fix (hack) for issue #44, there's probably a better way though.

### CODE REVIEW

**Comment by joaotavora** [comment]
Doesn't sound so hacky, considering the problem.  I'm tempted to merge it right away.  How's that copyright assignment coming along?

**Comment by mkcms** [comment]
> How's that copyright assignment coming along?

I already signed and sent the papers like a month ago. Just recently I was informed that the copyright clerk left the FSF in the meantime, so I don't know when the process will be finished.

**Comment by joaotavora** [comment]
@mkcms, I've thought a little about this, and the correct way is to remove this buffer from the list of buffers managed by eglot, since it has now changed major mode (and that is one of the fundamental variables for eglot).

I'm still thinking for the correct way to do this.  In the meanwhile, do you think this problem happens very often?

> I already signed and sent the papers like a month ago. Just recently I was informed that the copyright clerk left the FSF in the meantime, so I don't know when the process will be finished.

Sorry I only saw later in the other issue that you had already commented on this.  If you've done all you need to do, then we should be OK.

**Comment by mkcms** [comment]
I'm closing this as it was fixed in 21886bedc344d69550e8bb1d56bc6608d1f65a07.

**Pull request closed without merging**
