### PR TITLE
Add a handle to control CCLS initialization

### LINKED ISSUE #370: eglot not respecting ccls-initialization-options
I specify the ccls-initialization-options through dir-locals.el in the base of the project.
But when eglot start indexting the files it is not respecting whitelist/blacklist directories. Instead it indexes the whole project.

When switching to lsp-mode I see that the same setup is being respected.
Is that an expected behavior?

This did not work for me:

```
 (nil . ((eglot-workspace-configuration
      . ((:ccls . (setq ccls-initialization-options `(:index (:blacklist ["test"]) :whitelist ["test2"])))))))

```

### PR DESCRIPTION
**Pull request by gagbo**
Fixes #370

And it probably helps #544

### CODE REVIEW

**Comment by gagbo** [comment]
- No idea why tests are failing
- No idea if the CI setup needs to get ccls just for this test (I tested with nix version of ccls)
- I have signed FSF paperwork and am waiting for counter-sign, but this is arguably a small enough change ? I mostly copy-pasted a java test, and the other addition is pretty small

**Comment by gagbo** [comment]
Looks like [ccls can use a --init flag](https://github.com/MaskRay/ccls/wiki/Customization#initialization-options) as well, but I don’t know how you would use that to set per-project settings. With dir-locals over eglot-server-programs ?

**Comment by joaotavora** [comment]
HI @gagbo , I'd rather we exhaust the possibilities of `eglot-workspace-configuration` that we're trying in #370.

**Comment by gagbo** [comment]
Closing as discussed in #370

**Pull request closed without merging**
