### PR TITLE
Add language server for PureScript

### PR DESCRIPTION
**Pull request by alternateved**
Hello, I would like to add support for PureScript. Please let me know if there is anything I would need to fix or change.

Best wishes,
alternateved

### CODE REVIEW

**Comment by nemethf** [comment]
Out of curiosity can you send the server's reply to the initialize request? I'm interested in the server's capabilities.  You can get it with `M-x eglot-events-buffer RET` once the connection is established.  Thank you.

**Comment by alternateved** [comment]
Of course.

```
[internal] Wed Mar 30 09:01:03 2022:
(:message "Running language server: purescript-language-server --stdio")
[client-request] (id:1) Wed Mar 30 09:01:03 2022:
(:jsonrpc "2.0" :id 1 :method "initialize" :params
          (:processId 10096 :rootPath "/home/alternateved/Code/purescript-book/exercises/chapter8/" :rootUri "file:///home/alternateved/Code/purescript-book/exercises/chapter8" :initializationOptions #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
                                                                                                                                                                                                                      ())
                      :capabilities
                      (:workspace
                       (:applyEdit t :executeCommand
                                   (:dynamicRegistration :json-false)
                                   :workspaceEdit
                                   (:documentChanges t)
                                   :didChangeWatchedFiles
                                   (:dynamicRegistration t)
                                   :symbol
                                   (:dynamicRegistration :json-false)
                                   :configuration t :workspaceFolders t)
                       :textDocument
                       (:synchronization
                        (:dynamicRegistration :json-false :willSave t :willSaveWaitUntil t :didSave t)
                        :completion
                        (:dynamicRegistration :json-false :completionItem
                                              (:snippetSupport :json-false :deprecatedSupport t :tagSupport
                                                               (:valueSet
                                                                [1]))
                                              :contextSupport t)
                        :hover
                        (:dynamicRegistration :json-false :contentFormat
                                              ["markdown" "plaintext"])
                        :signatureHelp
                        (:dynamicRegistration :json-false :signatureInformation
                                              (:parameterInformation
                                               (:labelOffsetSupport t)
                                               :activeParameterSupport t))
                        :references
                        (:dynamicRegistration :json-false)
                        :definition
                        (:dynamicRegistration :json-false :linkSupport t)
                        :declaration
                        (:dynamicRegistration :json-false :linkSupport t)
                        :implementation
                        (:dynamicRegistration :json-false :linkSupport t)
                        :typeDefinition
                        (:dynamicRegistration :json-false :linkSupport t)
                        :documentSymbol
                        (:dynamicRegistration :json-false :hierarchicalDocumentSymbolSupport t :symbolKind
                                              (:valueSet
                                               [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]))
                        :documentHighlight
                        (:dynamicRegistration :json-false)
                        :codeAction
                        (:dynamicRegistration :json-false :codeActionLiteralSupport
                                              (:codeActionKind
                                               (:valueSet
                                                ["quickfix" "refactor" "refactor.extract" "refactor.inline" "refactor.rewrite" "source" "source.organizeImports"]))
                                              :isPreferredSupport t)
                        :formatting
                        (:dynamicRegistration :json-false)
                        :rangeFormatting
                        (:dynamicRegistration :json-false)
                        :rename
                        (:dynamicRegistration :json-false)
                        :publishDiagnostics
                        (:relatedInformation :json-false :codeDescriptionSupport :json-false :tagSupport
                                             (:valueSet
                                              [1 2])))
                       :experimental #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
                                                   ()))
                      :workspaceFolders
                      [(:uri "file:///home/alternateved/Code/purescript-book/exercises/chapter8" :name "~/Code/purescript-book/exercises/chapter8/")]))
```

**Comment by nemethf** [comment]
That's the request, I'm interested in the response to this.  It should start something like this:
```
[server-reply] (id:1) Wed Mar 30 18:10:12 2022:
(:jsonrpc "2.0" :id 1 :result
          (:capabilities
           (:textDocumentSync
```
Thanks again.

**Comment by alternateved** [comment]
Ah, my bad. I have added that part and then removed it, by mistake. Here it is:
```
[server-reply] (id:1) Wed Mar 30 18:17:08 2022:
(:jsonrpc "2.0" :id 1 :result
          (:capabilities
           (:textDocumentSync 1 :completionProvider
                              (:resolveProvider :json-false :triggerCharacters
                                                ["."])
                              :codeLensProvider
                              (:resolveProvider :json-false)
                              :hoverProvider t :definitionProvider t :workspaceSymbolProvider t :documentSymbolProvider t :codeActionProvider
                              (:codeActionKinds
                               ["" "source.organizeImports" "source.sortImports" "source.fixAll" "source"])
                              :executeCommandProvider
                              (:commands
                               ["purescript.addCompletionImport" "purescript.caseSplit-explicit" "purescript.addClause-explicit" "purescript.replaceSuggestion" "purescript.build" "purescript.clean" "purescript.startPscIde" "purescript.stopPscIde" "purescript.restartPscIde" "purescript.typedHole-explicit" "purescript.replaceAllSuggestions" "purescript.fixTypo"])
                              :referencesProvider t :foldingRangeProvider t :documentFormattingProvider t)))
 ```

**Comment by alternateved** [comment]
Hello, is there anything that needs to be fixed or changed in regards to that PR?

**Comment by joaotavora** [comment]
yes, don't do unsolicited whitespace changes and try to mimic exactly what the latest commits (including the commit messages) do for adding new servers to the out-of-box support.  It's a lot of little details, but then again, not that many details, and you seem to have most of them fixed already.

**Comment by joaotavora** [comment]
Thanks!

**Comment by alternateved** [comment]
Thanks for guidance!

**Pull request merged**
