### PR TITLE
Add up-to-date server executables for HTML/CSS/JSON

### PR DESCRIPTION
**Pull request by leungbk**
* README.md: Advertise updated executables.
* eglot.el (eglot-server-programs): Prioritize the alternatives.

The {html,css,json}-languageserver executables that are distributed
outside VS Code are not regularly updated by Microsoft; any relevant
updates to the VS Code source tree reach VS Code users without the
need for VS Code developers to go out of their way to publish new
versions of the executables. Consequently, users of other editors who
have been using the server executables from the most obvious NPM
installation are likely using stale versions.

GH hrsh7th, a Vim user, created an NPM package with updated versions
of these executables taken straight from VS Code's source tree. We
therefore prefer to direct users to this other repo, which contains
the appropriate NPM installation instructions, in the README.

The second commit forces `eglot-alternatives` to work with the
listified form, allowing presumed executables provided as
(EXECUTABLE &rest ARGS...)  to be displayed in the error.

cc @skangas

### CODE REVIEW

**Comment by skangas** [comment]
LGTM. @joaotavora do you have anything to add?

Thanks!

**Comment by joaotavora** [comment]
@leungbk I understand the first part just found. But what is then the motivation for the second part about `eglot-alternatives`?

**Comment by joaotavora** [comment]
Ok, I think I understand. My goal was to print more of the alternative for debug purposes, but the user facing result is probably poorer like that. So LGTM too.

If there's one thing I would change it would be to phrase the subject line as one simple sentence. Instead of:

```
update-alternstives: properly print foo
```

I would use:

```
Per #776: Properly print foo in update-alternatives
```

Or just


```
Per #776: Properly print error message of foo
```

That's just style preference because I find using the valuable small space of the subject line more useful for expressing the intention than the locus of a change, which is clear from the rest of the message.

But this is very minor and Stefan is now heading this, so whatever he's happy with counts. Just trying to shed light on my undocument practice of the last few years here.

**Comment by skangas** [comment]
> That's just style preference because I find using the valuable small space of the subject line more useful for expressing the intention than the locus of a change, which is clear from the rest of the message.

Yes, that looks like a good style. Let's stay consistent.

@leungbk Do you mind updating the commit messages as João suggests?

**Comment by leungbk** [comment]
@skangas Done.

**Comment by skangas** [comment]
Thanks! Now merged to master.

**Pull request merged**
