### PR TITLE
add lua-lsp for lua-mode

### PR DESCRIPTION
**Pull request by omar-polo**
Hello,

trivial patch to add `lua-lsp` for lua-mode.  I've just started to play with lua, but with this plus a `.luacompleterc` file I'm able to get completions for both built-in functions and external modules.

Cheers

edit: I wasn't sure what's the correct order is, so I added lua as last entry.

### CODE REVIEW

**Comment by joaotavora** [comment]
Can you add an entry to README.md and format the commit message like the other commit messages that do similar changes for adding a server?  That will make it easier for me to press the big green button and merge in your change.

**Comment by omar-polo** [comment]
sorry for the delay,

PR updated with the missing mention in the readme and the ChangeLog style commit message, hope I haven't missing anything this time! :)

I've seen that similar commits have a `Copyright-paperwork-exempt: yes` and while my change is small enough to not trigger the copyright issue, I do have a copyright assigment and have [previously contributed to emacs](https://github.com/emacs-mirror/emacs/commits?author=omar-polo).  I can always amend the commit message and add the "papewrork-exempt" anyway if needed, just let me know.

cheers,

**Comment by omar-polo** [comment]
friendly ping :)

**Comment by skangas** [comment]
Now merged to master. Thanks for your contribution!

**Comment by omar-polo** [comment]
thanks :)

**Pull request merged**
