### PR TITLE
Easier initializationOptions in eglot-server-programs

### PR DESCRIPTION
**Pull request by joaotavora**
* NEWS.md: Update.

* eglot.el (eglot-server-programs): Document new syntax.
(eglot-initialization-options): Can use initializationOptions from
server's saved initargs.
(eglot--connect): Allow a plist to be appended to a server
contact.

### CODE REVIEW

**Comment by joaotavora** [comment]
@nemethf @enderger @TLATER What do you think of this?  Could be useful?

**Comment by joaotavora** [comment]
This is 100% untested by the way...

**Comment by TLATER** [comment]
Yep! More intuitive than overriding functions, actually documented and already applied to the correct server :) I'm assuming this resolves at the right time so any `.dir-locals.el` has already been evaluated?

**Comment by nemethf** [comment]
Since eglot-server-programs  already has :autoport, I think this a simple and logical extension of the syntax.  Although, I don't understand why OPTIONS is either a plist or a function, the specification says it can be LSP-ANY.  Although it seems the code works as expected, it is just a documentation that needs adjusting.

```
export type LSPAny = LSPObject | LSPArray | string | integer | uinteger | decimal | boolean | null;
```

Do I understand correctly that this is future proof as it leaves room for additional keyword arguments in the specification of a server-program?

Should the commit log cite #845? (and possible other relevant discussions, issues)

Also, maybe I misremembering but when people complained about how they cannot set initializationOptions, it usually turned out they didn't need to set it in the first place.  This is nevertheless a good change.

(I haven't tested it either.)

**Comment by joaotavora** [comment]
>  Although, I don't understand why OPTIONS is either a plist or a function, the specification says it can be LSP-ANY. 

It's not to do with the _type_ of the value, but rather to _when_ it is obtained:

* When not using a funtion, the value is hardcoded in `eglot-server-programs` and as such can't depend on anything but the context that was present when `eglot-server-programs` was last set.  
* When it is a function, the calculation of whatever ends up in `initializeOptions` is delayed, so that you have access to the `eglot-lsp-server` instance containing project roots, major mode, etc.

Both are useful.

> Do I understand correctly that this is future proof as it leaves room for additional keyword arguments in the specification of a server-program?

Yes, but let's leave that undocumented for now.

> Should the commit log cite https://github.com/joaotavora/eglot/discussions/845? (and possible other relevant discussions, issues)

Yes, good idea.

> Also, maybe I misremembering but when people complained about how they cannot set initializationOptions, it usually turned out they didn't need to set it in the first place. This is nevertheless a good change.

They _can_ set it with by adding a method to `eglot-initialization-options` but that frequently requires a custom server class, which is cumbersome.  But you're right that in many situations these initialization options are best done via normal command line parameters.

**Comment by nemethf** [comment]
> > Although, I don't understand why OPTIONS is either a plist or a function, the specification says it can be LSP-ANY.
> 
> It's not to do with the _type_ of the value, but rather to _when_ it is obtained:
> [...] 
> Both are useful.

What I'm trying to say is when it's not a function, it can be also be a string, not just a plist as the proposed documentation states.

And I still think this is a good idea in general.

**Comment by joaotavora** [comment]
> it can be also be a string, not just a plist as the proposed documentation states.

Ahh, OK, I get it.  But then also when it is a function, the function can return a string if it wants to.

**Pull request closed without merging**
