### PR TITLE
Add examples to readme

### PR DESCRIPTION
**Pull request by andyleejordan**
I added two tricky (but probably) common problems and their solutions to the readme.

### CODE REVIEW

**Comment by andschwa** [comment]
I only changed the readme, shouldn't have affected these tests.

**Comment by andschwa** [comment]
I actually went looking for these examples in the readme yesterday, vaguely remembering having figured it out but not remembering where I'd written them down 😅 @joaotavora any chance this could be merged? It's documentation so it should again be copyright exempt, and I have yet again pinged the FSF copyright clerk to see the status of the now year-long process of getting my papers accepted.

**Comment by joaotavora** [comment]
I think this looks mostly good yes, but I don't think documentation is copyright exempt, no, sorry.  It's odd that it's taking so long, maybe you should bring this up to Eli Zaretskii or Lars Ingebrigsten on emacs-devel.

**Comment by andschwa** [comment]
Still never managed to get that copyright assignment paperwork approved by the FSF and I have given up bugging the clerk. I'm "next in line" but it's been months like that now. Just closing this. Thanks anyway @joaotavora!

**Comment by skangas** [comment]
@andschwa What is the current status with your copyright assignment? Did they sort this out? Otherwise, I will ask the right people to make them prioritize the request. Thanks!

**Comment by andschwa** [comment]
@skangas They never sorted it out! Last I heard I was "next in line" but have not heard that it's been resolved.

**Comment by skangas** [comment]
Thank you, I will make an attempt to contact the right people.

**Comment by skangas** [comment]
Just a brief update: Emacs co-maintainer Eli Zaretskii has reached out to the copyright clerk about this, so hopefully we should hear back from them soon.

**Comment by andschwa** [comment]
@skangas so...did they ever get that in? I've stopped hearing back from the copyright clerk.

**Comment by joaotavora** [comment]
> did they ever get that in? 

I don't think they did.  I still don't see your name in the copyright list. I apologize for the delay.  Please write to `emacs-devel@gnu.org`  and briefly explain the situation.

**Comment by andyleejordan** [comment]
I'm closing this because I was never able to get the copyright clerk to follow up on the paperwork I submitted...pre-covid.

**Pull request closed without merging**
