### PR TITLE
Allow staying out of flymake-mode, eldoc-mode

### PR DESCRIPTION
**Pull request by astoff**
One might wish not to have those Flymake hints in every buffer all the time.

### CODE REVIEW

**Comment by nemethf** [comment]
I wonder whether similar effects are achievable with `eglot-ignored-server-capabilites`. Nevertheless, I think providing alternative solutions to the same problem is a good thing.

**Comment by astoff** [comment]
So currently `flymake-mode` and `eldoc-mode` are turned on even if the corresponding server capability is ignored? We should fix that.

Now, I don't see the point of adding diagnostics and signature help to `eglot-ignored-server-capabilites`, since not activating Flymake or Eglot effectively ignores those capabilities. Staying out of Eldoc or Flymake is not equivalent — it allows turning on these modes later by hand. I don't know if anyone would care about this for Eldoc, but I do for Flymake.

**Comment by joaotavora** [comment]
> currently flymake-mode and eldoc-mode are turned on even if the corresponding server capability is ignored? We should fix that.

I agree and I think that @nemethf also stated he agrees. But please check for the symbols 'flymake and 'eldoc instead of flymake-mode and eldoc-mode.

**Comment by nemethf** [comment]
> > currently flymake-mode and eldoc-mode are turned on even if the corresponding server capability is ignored? We should fix that.
> 
> I agree and I think that @nemethf also stated he agrees. 

I did agree to the original PR, but @astoff's question sheds light on another issue.  If both hoverProvider and signatureHelpProvider is in eglot-ignored-server-capabilites, then it's unnecessary (or annoying) to mess with eldoc variables.  

Also, it seems to me that there's no server capability to inform the client about the server's ability to send diagnostics.  The client can advertise its capability to receive diagnostics in clientCapabilities.textDocument.publishDiagnostics.  But Eglot doesn't have ignored-client-cababilites, which is one more reason to go on with this PR.

**Comment by astoff** [comment]
> Also, it seems to me that there's no server capability to inform the client about the server's ability to send diagnostics.

This is very unfortunate, depressing even.

For Eldoc, we could test if the server has the relevant capabilities. But turning Eldoc on without necessity seems much less intrusive than turning Flymake on without necessity, so maybe it's better to keep it simple, i.e., as in the current version of the PR?

> But please check for the symbols 'flymake and 'eldoc instead of flymake-mode and eldoc-mode.

Done.

**Comment by astoff** [comment]
In light of @nemethf's last observations, I think the current form of the PR is a reasonable simple solution. Trying to make things too smart here would be kind of pointless.

**Comment by joaotavora** [comment]
Agree. Merged this, thanks.

**Pull request merged**
