### PR TITLE
Add yaml-language-server for yaml-mode

### PR DESCRIPTION
**Pull request by leungbk**
* eglot.el (eglot-server-programs): Add yaml-language-server

* README.md: mention yaml-language-server

Copyright-paperwork-exempt: yes

### CODE REVIEW

**Comment by R0flcopt3r** [comment]
Does this work for you? On my end I get this error:

```
[server-notification] Wed Dec 29 11:04:30 2021:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:type 1 :message "Notification handler 'initialized' failed with message: Client doesn't support sending workspace folder change events."))
```

**Comment by R0flcopt3r** [comment]
I think my emacs had some wonkey state, I have no been able to replicate it, and it seems to work just fine now.

**Comment by skangas** [comment]
@joaotavora This LGTM, WDYT?

**Comment by joaotavora** [comment]
@skangas, yes it looks good. There's a small conflcit in README.md, which is typical off these kind of "add language server" commits.  Else it looks good. I think (but not sure), that @leungbk , Brian,  already has at least one "Copyright-paperwork-exempt: Yes" commit but I don't think these lines would bring the total over the 15-line threshold.  So feel free to integrate into `master`  (via rebase and/or squash, preferably, as you did in other occasions)

**Comment by skangas** [comment]
@joaotavora Thanks. Could you please double-check if this is okay for copyright purposes? I fear that it is above the limit, but I'm not sure.

This is the `git log --author="Brian Leung" --stat --format=short` output, including this change:

```
commit 6acecf43451eb87f0a4748118c740417cff7a234 (HEAD -> yaml)
Author: Brian Leung <leungbk@posteo.net>

    Add yaml-language-server for yaml-mode

 README.md | 2 ++
 eglot.el  | 1 +
 2 files changed, 3 insertions(+)

commit 194b178ef41ccd3d937983f3829d44a546bb24d6
Author: Brian Leung <leungbk@mailfence.com>

    Close #712: Add support for LocationLink

 eglot.el | 25 ++++++++++++++++++-------
 1 file changed, 18 insertions(+), 7 deletions(-)

commit 47f8581434f5f853ff209538e5ee6e752f741d3c
Author: Brian Leung <29217594+leungbk@users.noreply.github.com>

    Per #605: indicate support for activeParameter

 eglot.el | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

commit c73f5ede8a9a52d6b4dabcd73f59b3a263c1b664
Author: Brian Leung <29217594+leungbk@users.noreply.github.com>

    Fix #612: remove duplicate entry for "Registration" LSP type

 eglot.el | 1 -
 1 file changed, 1 deletion(-)

commit 133c25e25f42ac16ee1c26a222d28d45fa566a64
Author: Brian Leung <29217594+leungbk@users.noreply.github.com>

    Close #613: explicitly require seq.el

 eglot.el | 1 +
 1 file changed, 1 insertion(+)

commit 1f2b0241ca24d78edbd146d17daef6a0e6b2e4f3
Author: Brian Leung <bkleung89@gmail.com>

    Close #605: Support activeParameter property for SignatureInformation

 eglot.el | 9 +++++----
 1 file changed, 5 insertions(+), 4 deletions(-)

commit e6ca70c3e049107d41cdc63d6414f4a3799a9e33
Author: Brian Leung <29217594+leungbk@users.noreply.github.com>

    Close #599: add rnix-lsp server for nix-mode, community suggestion

 README.md | 2 ++
 eglot.el  | 1 +
 2 files changed, 3 insertions(+)
```

**Comment by leungbk** [comment]
I’ve signed all the copyright papers already, so I don’t think there should
be a problem.

**Comment by skangas** [comment]
> I’ve signed all the copyright papers already, so I don’t think there should be a problem.

Thanks, I can see your commits in emacs.git, so there should be no problem here.

**Comment by skangas** [comment]
Now merged to master, thanks for your contribution!

**Comment by joaotavora** [comment]
Yes, and I forgot that Brian had indeed already done a Copyright Assignemnt.  Sorry about the noise. @skangas you can ask Eli for a "fencepost account" where you can do this checking yourself.

**Pull request merged**
