### PR TITLE
Remote server/TRAMP support (fix #84)

### LINKED ISSUE #84: could eglot work with remote project?
hi,
Say a project is on a remote raspberry pi, I have emacs installed on local desktop. When the project file is opened by the desktop emacs (say using tramp), can I get the open file indexed? 

Specificly, the project is a cpp project, the toolchain is only availabe on the remote pi. So the lsp server is better running on the remote pi. Can I get it work by eglot? 

Thanks!

### PR DESCRIPTION
**Pull request by FelipeLema**
Support remote files / tramp.

### CODE REVIEW

**Comment by joaotavora** [comment]
Hi @FelipeLema this looks good in general. But (as you probably already know)

* it is existing failing tests;

* it needs existing tests (how?);

* some of the function names are hard to understand;

* your formatting choices go against mine, so unless you feel very strongly about them, later on, I will ask you to review them.

**Comment by joaotavora** [comment]
> it needs existing tests (how?);

Duh, I meant "new tests"

**Comment by FelipeLema** [comment]
>     it is existing failing tests;

yup, I'm using travis as checker for now. This is why I'm doing this as a /draft/ pull request

>     it needs existing tests (how?);

I'm aware of this. For now, I'm working on unbreaking tests. Once I have that, will work out a way to test this. The way I see it, re-running the same tests using `/ssh:localhost;/some/path` should be enough, so I might end up adding a meta-config.

>     some of the function names are hard to understand;
Please, point them out, so I can address them directly. Naming in this context is real hard.

>     your formatting choices go against mine, so unless you feel very strongly about them, later on, I will ask you to review them.

I noticed that some alignment went different, but it was unintended. I'll add a TODO for them.

**Comment by garyo** [comment]
Hope you don't mind someone chiming in on this. Your work might help my case: I run Emacs on Windows, but all the rest of my development environment is in Linux using WSL on the same machine. So it's not remote as such. Right now I'm installing the language server on the Windows side just so eglot and intellisense will work; I'd love to use the Linux-side language server, but there's a filename translation problem. Windows `c:/foo/bar` becomes `/mnt/c/foo/bar` in Linux (with default mappings anyway). If in the work you're doing here, you could allow for a filename-mapping hook (i.e. between Emacs's idea of filename and the server's idea), so I could use the Linux language server, people in my situation would be very grateful! (Note that it's no problem for Windows Emacs to start a Linux process using WSL, and get its stdio and so on. It's just the filename mapping at issue.)

**Comment by joaotavora** [comment]
> Hope you don't mind someone chiming in on this

Not at all.

> the work you're doing here, you could allow for a filename-mapping hook (i.e. between Emacs's idea of 

This looks like a simpler addition, but at any rate a prerequisite for TRAMP support. 

You should be able to achieve a bit of this hooking if you `advice-add` to `eglot--path-to-uri` and `eglot--uri-to-path`.

We could ask @FelipeLema to split his PR into two parts.  One that supplies this indirection, and another one with TRAMP support that will surely use this indirection.  However, if that confuses or complicates Felipe's TRAMP goal, I'd rather it waits a bit.

**Comment by FelipeLema** [comment]
I guess I could add some code for url and path treatment, but that might end up bloating up the code.

@garyo can you open an issue so we can discuss a (quicker) solution to your problem?

**Comment by joaotavora** [comment]
> @garyo can you open an issue so we can discuss a (quicker) solution to your problem?

That's probably a good idea, yes.

**Comment by FelipeLema** [comment]
I have several reasons to not continue with this Pull Request

- I have `eglot` working with tramp, but inconsistently... it seems I'm missing some low-level config/way of doing things (program setup works OK with small tests, language server program is getting incomplete strings/bytes). It's definitely *not* easy to debug and find out just what.
- There are several tramp tools/functionalities from Emacs 27 not present in 26 that need to be re-written. I've tried this, but have been getting inconsistent results.
- When 27 arrives (at [my system](voidlinux.org)), I will pick up this feature. This branch/PR is mostly patching things to get it working in 26, so these changes are mostly noise with 27 available.

**Pull request closed without merging**
