### PR TITLE
Add a simple github issue template

### PR DESCRIPTION
**Pull request by nemethf**
Background info: https://help.github.com/en/articles/about-issue-and-pull-request-templates

Hopefully, this template leads towards fewer back-and-forth
communication, detailed bug reports, and easier maintainership.

* .github/ISSUE_TEMPLATE/bug_report.md: New file.

### CODE REVIEW

**Comment by joaotavora** [comment]
This is a good idea, but what does it do exactly when one creates a new issue?  Does it just add the text pointing to the homepage?

**Comment by nemethf** [comment]
> Does it just add the text pointing to the homepage?

Yes, and unfortunately the text will be in the issue if the reporter doesn't delete it.  And it also complicates the bug reporting process by forcing the user to click on an additional link.

Other projects make the reporting process more complicated.  For example, select the 'Bug Report' option from here: https://github.com/kubernetes-sigs/kubespray/issues/new/choose

But I hope a simple notice would be enough.

**Comment by nemethf** [comment]
@joaotavora, would it be okay to temporary enable this feature of github and see if it makes any difference?

**Comment by joaotavora** [comment]
I guess, yes, go for it.  Maybe you could also repeat the text in the README in the template. But maybe repetition is not a good idea.  Your call.

**Comment by nemethf** [comment]
Thanks.  I've just pushed the simple template.  If it's not enough, we can enhance it later.

**Pull request closed without merging**
