### PR TITLE
Add support for optional CompletionItem.tags

### PR DESCRIPTION
**Pull request by leungbk**
* eglot.el (eglot--lsp-interface-alist): Add optional CompletionItem.tags.
(eglot-completion-at-point): Add :company-deprecated key and value.

### CODE REVIEW

**Comment by skangas** [comment]
Thanks! Should we have a test case for this?

**Comment by skangas** [comment]
Another thing, should this be mentioned under "Supported Protocol features" in README.md? I guess I have the same question for diagnostic tags.

**Comment by joaotavora** [comment]
@skangas That section hasn't been updated in a long time.  Not sure it is very accurate  and/or useful.  Maybe it is, maybe not. Maybe it can be generated automatically from the code? Just wanted to note that if you want to kill it or somehow transform it, feel free to.

**Comment by skangas** [comment]
> @skangas That section hasn't been updated in a long time. Not sure it is very accurate and/or useful. Maybe it is, maybe not. Maybe it can be generated automatically from the code? Just wanted to note that if you want to kill it or somehow transform it, feel free to.

Thanks. This is somewhat off-topic but did you ever consider writing an info manual for eglot?

**Comment by skangas** [comment]
Actually, I think we could just delete it, especially if it doesn't accurately reflect the status of the code. Any interested party will be able to see what is supported or not from reading the code and/or testing.

The README is rather long as it is, and if we want to re-add something like that later, we can just find the previous work in the git log.

**Comment by joaotavora** [comment]
The first draft of that info manual would be written from snippets of the README.md of course.  Maintaining both the info manual _and_ the README.md doesn't make much sense to me.

**Comment by joaotavora** [comment]
> FWIW, I think C-h S sort of sucks in its current form; it really should include other info manuals as well.

Right, but that's some problem that isn't easy to solve apparently (there was some discussion in emacs-devel and in the bug tracker about it some time ago). 

Note that one of the advantages of having Eglot in core is that other packages (notably major modes), can take advantage of its Elisp API directly (and help grow that API). So the Elisp info manual is also relevant here.

**Comment by leungbk** [comment]
> Thanks! Should we have a test case for this?

The reason I didn't write a test for this is that what may be considered "deprecated" by a server today may not be offered as a completion at all in a newer version of the same server.

We could work around this by using the Nix package manager for our test suite and pinning nixpkgs to a specific revision, ensuring that the same version of a server is used every time. Maybe that's better in another PR though.

**Comment by skangas** [comment]
Yes, that's a fair point. Unless we can find a language with the same 10 year+ obsoletion policy as GNU Emacs, I guess.

I can agree that further work on our test suite is probably best left for another PR. In general, I think it needs work, in particular it would be nice if it was easier to run it without installing a gazillion language servers manually. I'm not sure what to do though: Guix, Docker, something else...

**Comment by skangas** [comment]
BTW, the commit has conflicts against current master. It would be great if you could fix them. Thanks.

**Comment by skangas** [comment]
Oh, and while I'm at it: do you think you could you write up a `NEWS.md` entry for this change? You can see the one I added for diagnostic tags for inspiration.

**Comment by nemethf** [comment]
> ... info manual ...

I hope the current readme won't disappear completely with the arrival of  a new, detailed manual.  Maybe the on-line documentation (the current readme) could be reduced to a small introduction with the current animgifs (which cannot be part of an info file) and a link to the detailed info documentation.

I was working on an eglot-find-documentation function (#792) to show the local README.  But the readme is hard to read without markdown-mode installed.  So, I tried to reformat the readme to README.org.  Theoretically github supports this format, emacs displays it without a third-party (non-gnu) package, and it can automatically exported into info files.  From a practical standpoint, however, it seems that in-file links either work in emacs or on github.  Additionally, I'm no info-expert, but exported info file is far from perfect.

Anyhow, here is [the github rendered version](https://github.com/nemethf/eglot/tree/org) of my README.org.

**Comment by skangas** [comment]
@nemethf FWIW, I see no problem with changing format of the README to org-mode, and some benefits including better built-in support, but I don't know what @joaotavora thinks about it.

**Comment by skangas** [comment]
Thanks for the recent changes @leungbk.

If you have it readily available, could you please tell me which language server you used to develop and test this, and perhaps even show a code snippet? Otherwise, I will try to figure out how to test it, but it'll take some more time.

**Comment by leungbk** [comment]
@skangas See https://github.com/leungbk/some-app.

**Comment by leungbk** [comment]
OK, so the `non-unique-completions` test passes on Emacs 27.1 and beyond (https://github.com/joaotavora/eglot/runs/4824915700?check_suite_focus=true#step:8:259), but fails on 26.3 (https://github.com/joaotavora/eglot/runs/4824915684?check_suite_focus=true#step:8:385). I'm not a Python expert, so I would appreciate some help debugging this.

**Comment by leungbk** [comment]
The stuff I submitted previously now passes for Emacs 26.3 if I `(eval-and-compile (require 'seq))` (no clue why).

Now I've added another commit that attempts to render the strike-through when using vanilla `M-x completion-at-point` without `company`. However, this is failing on 26.3 and passing on the other Emacsen. 26.3 complains about a void `seq-contains-p` even though it's clearly `eval-and-compile`d and `require`d up top. Not sure what's going on.

**Comment by leungbk** [comment]
I suppose another question is: do we even care about supporting vanilla `M-x completion-at-point`? Virtually every `eglot` user is going to have `company` or @minad's `corfu` (which reads the `:company-deprecated` thing anyway) installed; for these users, adding the extra lookup is a waste of computing time/electricity.

**Comment by skangas** [comment]
I think you just end up using a too old version of `seq` on 26.3. Does it work better if you do this?
```
diff --git a/Makefile b/Makefile
index 2b3c33d..58048d3 100644
--- a/Makefile
+++ b/Makefile
@@ -22,6 +22,7 @@ ELPADEPS ?=--eval '(setq package-user-dir (expand-file-name "elpa-eglot-test" te
            --eval '(install-latest (quote jsonrpc))'            \
            --eval '(install-latest (quote project))'            \
            --eval '(install-latest (quote xref))'               \
+	   --eval '(install-latest (quote seq))'                \
            --eval '(install-latest (quote eldoc))'              \
            --eval '(unintern                                    \
                      (quote eldoc-documentation-function))'     \
```

**Comment by skangas** [comment]
> I suppose another question is: do we even care about supporting vanilla `M-x completion-at-point`? Virtually every `eglot` user is going to have `company` or @minad's `corfu` (which reads the `:company-deprecated` thing anyway) installed;

I think we should still support it, yes. Not all users will be using those packages, either because they don't know about them or because their preferences are just different.

I'm not sure about this, but I believe there are packages that build other features on top of a working `completion-at-point`.

**Comment by dgutov** [comment]
If someone really wanted, they could add `:company-deprecated` support to the vanilla `completion-at-point` itself.

Completion backends shouldn't much around with faces directly.

**Comment by skangas** [comment]
> Completion backends shouldn't much around with faces directly.

Hmm, are you saying that this patch is doing something wrong? What should it be doing instead?

**Comment by leungbk** [comment]
> I think you just end up using a too old version of `seq` on 26.3. Does it work better if you do this?

No, same result.

**Comment by leungbk** [comment]
Whatever, I used `cl-loop` instead of `seq-contains-p` since I don't want to fuss over this.

I also dropped the vanilla `cap` rendering per Dmitry's suggestion.

**Comment by skangas** [comment]
> @skangas See https://github.com/leungbk/some-app.

Thanks for the clear instructions. I tried opening `some-app/src/Thing.js`, then I typed `this.refs`. `refs` now has strike-out, which seems like what we expect.

When I move the cursor from `refs` and back again, I see that the message `typescript: 'refs' is deprecated` flashes in the minibuffer and is within less than half a second replaced by another message containing the type signature followed by a single line `@deprecated - https://reactjs.org/docs/refs-and-the-dom.html#legacy-api-string-refs`.

I have two questions:
1. How do I open that URL without manually typing it into some web browser? I guess this is a problem unrelated to this particular issue, but I feel like I am missing something.
2. Do we really want two messages here? The first one flashes too quickly to be readable, so I'm wondering if we could/should get rid of it.

**Comment by leungbk** [comment]
> 1. How do I open that URL without manually typing it into some web browser? I guess this is a problem unrelated to this particular issue, but I feel like I am missing something.

I haven't dug into this too much, but I am guessing the first message is from a server Diagnostic, while the second one is related to a SignatureInformation. The SignatureInformation interface does not have any kind of separate field for a URL, so I suspect it is a part of the SignatureInformation's `documentation` property.

I don't think we presently have any good way of quickly opening that URL via Eldoc.

> 2. Do we really want two messages here? The first one flashes too quickly to be readable, so I'm wondering if we could/should get rid of it.

I don't know a good way of deciding which message to prioritize since the messages correspond to different requests. Also, I don't think we can necessarily assume that all SignatureInformation objects redundantly indicate deprecation.

**Comment by skangas** [comment]
Thanks for this! Now merged to master.

**Pull request merged**
