### PR TITLE
Add option 'eglot-show-hover-help-p'

### PR DESCRIPTION
**Pull request by manateelazycat**
Hi João

Eglot is awesome, but i don't like it show help document in minibuffer when cursor hover string.

So i add option 'eglot-show-hover-help-p' to control whether show help document when cursor hover.

Thanks you for your great job!

### CODE REVIEW

**Comment by mkcms** [comment]
You should do this instead:
```elisp
(setq eglot-ignored-server-capabilites '(:hoverProvider))
```

**Comment by joaotavora** [comment]
> (setq eglot-ignored-server-capabilites '(:hoverProvider))

Yep :-)

**Comment by manateelazycat** [comment]
Wow, thanks all!

**Comment by joaotavora** [comment]
> Wow, thanks all!

You're welcome. Thanks for the PR anyway.

**Pull request closed without merging**
