### PR TITLE
Close #54: Convert to lsp position correctly when buffer is narrowed

### LINKED ISSUE #54: Wrong :character position is reported by eglot's text sync functions when narrowing is in effect
When I use clangd and have a buffer with these contents:

```c
int main()
{
    return;
}
```

and I narrow to the word `return`, and then insert ` 0` (space + 0) at the end of of the buffer, eglot sends the following notification to the server:

```
(:jsonrpc "2.0" :method "textDocument/didChange" :params
	  (:textDocument
	   (:uri "file:///tmp/proj/src/main.c" :version 4)
	   :contentChanges
	   [(:range
	     (:start
	      (:line 2 :character 6)
	      :end
	      (:line 2 :character 6))
	     :rangeLength 0 :text " ")
	    (:range
	     (:start
	      (:line 2 :character 7)
	      :end
	      (:line 2 :character 7))
	     :rangeLength 0 :text "0")]))

```

which is wrong, because the range of characters where the buffer changed is line 2, characters 10-11. 
Eglot treats `point-min` as beginning of line in that case.

### PR DESCRIPTION
**Pull request by mkcms**
* eglot.el (eglot--pos-to-lsp-position): Fix return value when
  narrowing is in effect.

### CODE REVIEW

**Comment by joaotavora** [comment]
I made a comment about `eglot--widening` otherwise looks great.

**Comment by mkcms** [comment]
> I made a comment about eglot--widening otherwise looks great.

Hmm, I can't see a comment. I refactored the code to use `eglot--widening` anyways, thanks.

**Comment by joaotavora** [comment]
> Hmm, I can't see a comment. 

Figures.  I didn't sumbit the review.

**Comment by joaotavora** [comment]
Pushed with a tweak to the commit headline

**Pull request merged**
