### PR TITLE
Fix #715: fix eglot-extend-to-xref under Windows

### LINKED ISSUE #715: `eglot-extend-to-xref` does not work well with gopls/clangd under Windows
* Server used:  gopls             
* Emacs version:   27.2          
* Operating system:  Windows 10        
* Eglot version:  1.7           
* Eglot installation method:  package.el     
* Using Doom:  No              

#### LSP transcript - M-x eglot-events-buffer (mandatory unless Emacs inoperable)

     
```lisp
... Paste the events transcript here ...  Try to start from the line that says
[client-request] (id:1) Sun Aug  1 09:04:44 2021:
(:jsonrpc "2.0" :id 1 :method "initialize" :params
	  (:processId 13220 :rootPath "f:/CASE-eglot/" :rootUri "file:///f:/CASE-eglot/" :initializationOptions #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
															      ())
		      :capabilities
		      (:workspace
		       (:applyEdit t :executeCommand
				   (:dynamicRegistration :json-false)
				   :workspaceEdit
				   (:documentChanges :json-false)
				   :didChangeWatchedFiles
				   (:dynamicRegistration t)
				   :symbol
				   (:dynamicRegistration :json-false)
				   :configuration t)
		       :textDocument
		       (:synchronization
			(:dynamicRegistration :json-false :willSave t :willSaveWaitUntil t :didSave t)
			:completion
			(:dynamicRegistration :json-false :completionItem
					      (:snippetSupport :json-false)
					      :contextSupport t)
			:hover
			(:dynamicRegistration :json-false :contentFormat
					      ["markdown" "plaintext"])
			:signatureHelp
			(:dynamicRegistration :json-false :signatureInformation
					      (:parameterInformation
					       (:labelOffsetSupport t)))
			:references
			(:dynamicRegistration :json-false)
			:definition
			(:dynamicRegistration :json-false)
			:declaration
			(:dynamicRegistration :json-false)
			:implementation
			(:dynamicRegistration :json-false)
			:typeDefinition
			(:dynamicRegistration :json-false)
			:documentSymbol
			(:dynamicRegistration :json-false :hierarchicalDocumentSymbolSupport t :symbolKind
					      (:valueSet
					       [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]))
			:documentHighlight
			(:dynamicRegistration :json-false)
			:codeAction
			(:dynamicRegistration :json-false :codeActionLiteralSupport
					      (:codeActionKind
					       (:valueSet
						["quickfix" "refactor" "refactor.extract" "refactor.inline" "refactor.rewrite" "source" "source.organizeImports"]))
					      :isPreferredSupport t)
			:formatting
			(:dynamicRegistration :json-false)
			:rangeFormatting
			(:dynamicRegistration :json-false)
			:rename
			(:dynamicRegistration :json-false)
			:publishDiagnostics
			(:relatedInformation :json-false))
		       :experimental #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
						   ()))))
[server-reply] (id:1) Sun Aug  1 09:04:44 2021:
(:jsonrpc "2.0" :result
	  (:capabilities
	   (:textDocumentSync
	    (:openClose t :change 2 :save nil)
	    :completionProvider
	    (:triggerCharacters
	     ["."]
	     :completionItem nil)
	    :hoverProvider t :signatureHelpProvider
	    (:triggerCharacters
	     ["(" ","])
	    :definitionProvider t :typeDefinitionProvider t :implementationProvider t :referencesProvider t :documentHighlightProvider t :documentSymbolProvider t :codeActionProvider
	    (:codeActionKinds
	     ["quickfix" "refactor.extract" "refactor.rewrite" "source.fixAll" "source.organizeImports"])
	    :codeLensProvider nil :documentLinkProvider nil :workspaceSymbolProvider t :documentFormattingProvider t :documentOnTypeFormattingProvider
	    (:firstTriggerCharacter "")
	    :renameProvider t :foldingRangeProvider t :executeCommandProvider
	    (:commands
	     ["gopls.add_dependency" "gopls.add_import" "gopls.apply_fix" "gopls.check_upgrades" "gopls.gc_details" "gopls.generate" "gopls.generate_gopls_mod" "gopls.go_get_package" "gopls.list_known_packages" "gopls.regenerate_cgo" "gopls.remove_dependency" "gopls.run_tests" "gopls.start_debugging" "gopls.test" "gopls.tidy" "gopls.toggle_gc_details" "gopls.update_go_sum" "gopls.upgrade_dependency" "gopls.vendor" "gopls.workspace_metadata"])
	    :callHierarchyProvider t :workspace
	    (:workspaceFolders
	     (:supported t :changeNotifications "workspace/didChangeWorkspaceFolders")))
	   :serverInfo
	   (:name "gopls" :version "{\"path\":\"golang.org/x/tools/gopls\",\"version\":\"v0.7.0\",\"sum\":\"h1:JQBHW81Gsyim6iDjUwGoPeSpXrSqwen3isPJLfDfaYU=\",\"deps\":[{\"path\":\"github.com/BurntSushi/toml\",\"version\":\"v0.3.1\",\"sum\":\"h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=\"},{\"path\":\"github.com/google/go-cmp\",\"version\":\"v0.5.5\",\"sum\":\"h1:Khx7svrCpmxxtHBq5j2mp/xVjsi8hQMfNLvJFAlrGgU=\"},{\"path\":\"github.com/sergi/go-diff\",\"version\":\"v1.1.0\",\"sum\":\"h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=\"},{\"path\":\"golang.org/x/mod\",\"version\":\"v0.4.2\",\"sum\":\"h1:Gz96sIWK3OalVv/I/qNygP42zyoKp3xptRVCWRFEBvo=\"},{\"path\":\"golang.org/x/sync\",\"version\":\"v0.0.0-20210220032951-036812b2e83c\",\"sum\":\"h1:5KslGYwFpkhGh+Q16bwMP3cOontH8FOep7tGV86Y7SQ=\"},{\"path\":\"golang.org/x/sys\",\"version\":\"v0.0.0-20210510120138-977fb7262007\",\"sum\":\"h1:gG67DSER+11cZvqIMb8S8bt0vZtiN6xWYARwirrOSfE=\"},{\"path\":\"golang.org/x/tools\",\"version\":\"v0.1.3-0.20210608163600-9ed039809d4c\",\"sum\":\"h1:Pv9gNyJFYVdpUAVZYJ1BDSU4eGgXQ+0f3DIGAdolO5s=\"},{\"path\":\"golang.org/x/xerrors\",\"version\":\"v0.0.0-20200804184101-5ec99f83aff1\",\"sum\":\"h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=\"},{\"path\":\"honnef.co/go/tools\",\"version\":\"v0.2.0\",\"sum\":\"h1:ws8AfbgTX3oIczLPNPCu5166oBg9ST2vNs0rcht+mDE=\"},{\"path\":\"mvdan.cc/gofumpt\",\"version\":\"v0.1.1\",\"sum\":\"h1:bi/1aS/5W00E2ny5q65w9SnKpWEF/UIOqDYBILpo9rA=\"},{\"path\":\"mvdan.cc/xurls/v2\",\"version\":\"v2.2.0\",\"sum\":\"h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=\"}]}"))
	  :id 1)
[client-notification] Sun Aug  1 09:04:44 2021:
(:jsonrpc "2.0" :method "initialized" :params #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
							    ()))
[client-notification] Sun Aug  1 09:04:44 2021:
(:jsonrpc "2.0" :method "textDocument/didOpen" :params
	  (:textDocument
	   (:uri "file:///f:/CASE-eglot/test.go" :version 0 :languageId "go" :text "package main\n\nimport \"math\"\n\nfunc main() {\n	print(math.Abs(-2.0))\n}\n")))
[client-notification] Sun Aug  1 09:04:44 2021:
(:jsonrpc "2.0" :method "workspace/didChangeConfiguration" :params
	  (:settings nil))
[client-request] (id:2) Sun Aug  1 09:04:44 2021:
(:jsonrpc "2.0" :id 2 :method "textDocument/documentSymbol" :params
	  (:textDocument
	   (:uri "file:///f:/CASE-eglot/test.go")))
[server-notification] Sun Aug  1 09:04:44 2021:
(:jsonrpc "2.0" :method "window/showMessage" :params
	  (:type 4 :message "Loading packages..."))
[server-request] (id:1) Sun Aug  1 09:04:44 2021:
(:jsonrpc "2.0" :method "workspace/configuration" :params
	  (:items
	   [(:scopeUri "file:///F:/CASE-eglot/" :section "gopls")])
	  :id 1)
[client-reply] (id:1) Sun Aug  1 09:04:44 2021:
(:jsonrpc "2.0" :id 1 :result
	  [nil])
[server-notification] Sun Aug  1 09:04:45 2021:
(:jsonrpc "2.0" :method "window/logMessage" :params
	  (:type 3 :message "2021/08/01 09:04:45 go env for F:\\CASE-eglot\\\n(root F:\\CASE-eglot\\)\n(go version go version go1.16 windows/amd64)\n(valid build configuration = true)\n(build flags: [])\nGOFLAGS=\nGOINSECURE=\nGONOPROXY=github.com/mtkgo\nGOPROXY=https://goproxy.cn,direct\nGOROOT=c:\\go\nGOCACHE=C:\\Users\\wsw\\AppData\\Local\\go-build\nGONOSUMDB=github.com/mtkgo\nGOPATH=C:\\Users\\wsw\\go\nGOPRIVATE=github.com/mtkgo\nGOSUMDB=sum.golang.org\nGO111MODULE=on\nGOMOD=F:\\CASE-eglot\\go.mod\nGOMODCACHE=C:\\Users\\wsw\\go\\pkg\\mod\n\n"))
[server-notification] Sun Aug  1 09:04:45 2021:
(:jsonrpc "2.0" :method "window/logMessage" :params
	  (:type 3 :message "2021/08/01 09:04:45 go/packages.Load\n	snapshot=0\n	directory=F:\\CASE-eglot\\\n	query=[builtin test/...]\n	packages=2\n"))
[server-notification] Sun Aug  1 09:04:45 2021:
(:jsonrpc "2.0" :method "window/showMessage" :params
	  (:type 3 :message "Finished loading packages."))
[server-request] (id:2) Sun Aug  1 09:04:45 2021:
(:jsonrpc "2.0" :method "client/registerCapability" :params
	  (:registrations
	   [(:id "workspace/didChangeWatchedFiles-0" :method "workspace/didChangeWatchedFiles" :registerOptions
		 (:watchers
		  [(:globPattern "F:\\CASE-eglot/**/*.{go,mod,sum,tmpl}" :kind 7)
		   (:globPattern "**/*.{go,mod,sum}" :kind 7)
		   (:globPattern "**/*.*tmpl" :kind 7)]))])
	  :id 2)
[client-reply] (id:2) Sun Aug  1 09:04:45 2021:
(:jsonrpc "2.0" :id 2 :result nil)
[server-request] (id:3) Sun Aug  1 09:04:45 2021:
(:jsonrpc "2.0" :method "workspace/configuration" :params
	  (:items
	   [(:section "gopls")])
	  :id 3)
[client-reply] (id:3) ERROR Sun Aug  1 09:04:45 2021:
(:jsonrpc "2.0" :id 3 :error
	  (:code -32603 :message "Internal error"))
[server-reply] (id:2) Sun Aug  1 09:04:45 2021:
(:jsonrpc "2.0" :result
	  [(:name "main" :detail "()" :kind 12 :range
		  (:start
		   (:line 4 :character 0)
		   :end
		   (:line 6 :character 1))
		  :selectionRange
		  (:start
		   (:line 4 :character 5)
		   :end
		   (:line 4 :character 9)))]
	  :id 2)
[client-request] (id:3) Sun Aug  1 09:05:18 2021:
(:jsonrpc "2.0" :id 3 :method "textDocument/signatureHelp" :params
	  (:textDocument
	   (:uri "file:///f:/CASE-eglot/test.go")
	   :position
	   (:line 0 :character 0)))
[client-request] (id:4) Sun Aug  1 09:05:18 2021:
(:jsonrpc "2.0" :id 4 :method "textDocument/hover" :params
	  (:textDocument
	   (:uri "file:///f:/CASE-eglot/test.go")
	   :position
	   (:line 0 :character 0)))
[client-request] (id:5) Sun Aug  1 09:05:18 2021:
(:jsonrpc "2.0" :id 5 :method "textDocument/documentHighlight" :params
	  (:textDocument
	   (:uri "file:///f:/CASE-eglot/test.go")
	   :position
	   (:line 0 :character 0)))
[server-reply] (id:3) Sun Aug  1 09:05:18 2021:
(:jsonrpc "2.0" :result nil :id 3)
[server-notification] Sun Aug  1 09:05:18 2021:
(:jsonrpc "2.0" :method "window/logMessage" :params
	  (:type 1 :message "2021/08/01 09:05:18 no signature help: cannot find an enclosing function\n	position={0 0}\n"))
[server-reply] (id:4) Sun Aug  1 09:05:18 2021:
(:jsonrpc "2.0" :result nil :id 4)
[server-reply] (id:5) Sun Aug  1 09:05:18 2021:
(:jsonrpc "2.0" :result
	  []
	  :id 5)
[client-request] (id:6) Sun Aug  1 09:05:19 2021:
(:jsonrpc "2.0" :id 6 :method "textDocument/signatureHelp" :params
	  (:textDocument
	   (:uri "file:///f:/CASE-eglot/test.go")
	   :position
	   (:line 5 :character 0)))
[client-request] (id:7) Sun Aug  1 09:05:19 2021:
(:jsonrpc "2.0" :id 7 :method "textDocument/hover" :params
	  (:textDocument
	   (:uri "file:///f:/CASE-eglot/test.go")
	   :position
	   (:line 5 :character 0)))
[client-request] (id:8) Sun Aug  1 09:05:19 2021:
(:jsonrpc "2.0" :id 8 :method "textDocument/documentHighlight" :params
	  (:textDocument
	   (:uri "file:///f:/CASE-eglot/test.go")
	   :position
	   (:line 5 :character 0)))
[server-reply] (id:6) Sun Aug  1 09:05:19 2021:
(:jsonrpc "2.0" :result nil :id 6)
[server-notification] Sun Aug  1 09:05:19 2021:
(:jsonrpc "2.0" :method "window/logMessage" :params
	  (:type 1 :message "2021/08/01 09:05:19 no signature help: cannot find an enclosing function\n	position={5 0}\n"))
[server-reply] (id:7) Sun Aug  1 09:05:19 2021:
(:jsonrpc "2.0" :result nil :id 7)
[server-reply] (id:8) Sun Aug  1 09:05:19 2021:
(:jsonrpc "2.0" :result
	  []
	  :id 8)
[client-request] (id:9) Sun Aug  1 09:05:20 2021:
(:jsonrpc "2.0" :id 9 :method "textDocument/signatureHelp" :params
	  (:textDocument
	   (:uri "file:///f:/CASE-eglot/test.go")
	   :position
	   (:line 5 :character 1)))
[server-reply] (id:9) Sun Aug  1 09:05:20 2021:
(:jsonrpc "2.0" :result nil :id 9)
[server-notification] Sun Aug  1 09:05:20 2021:
(:jsonrpc "2.0" :method "window/logMessage" :params
	  (:type 1 :message "2021/08/01 09:05:20 no signature help: cannot find an enclosing function\n	position={5 1}\n"))
[client-request] (id:10) Sun Aug  1 09:05:21 2021:
(:jsonrpc "2.0" :id 10 :method "textDocument/signatureHelp" :params
	  (:textDocument
	   (:uri "file:///f:/CASE-eglot/test.go")
	   :position
	   (:line 5 :character 13)))
[client-request] (id:11) Sun Aug  1 09:05:21 2021:
(:jsonrpc "2.0" :id 11 :method "textDocument/hover" :params
	  (:textDocument
	   (:uri "file:///f:/CASE-eglot/test.go")
	   :position
	   (:line 5 :character 13)))
[client-request] (id:12) Sun Aug  1 09:05:21 2021:
(:jsonrpc "2.0" :id 12 :method "textDocument/documentHighlight" :params
	  (:textDocument
	   (:uri "file:///f:/CASE-eglot/test.go")
	   :position
	   (:line 5 :character 13)))
[server-reply] (id:10) Sun Aug  1 09:05:21 2021:
(:jsonrpc "2.0" :result
	  (:signatures
	   [(:label "print(args ...Type)" :documentation "The print built-in function formats its arguments in an\nimplementation-specific way and writes the result to standard error.\nPrint is useful for bootstrapping and debugging; it is not guaranteed\nto stay in the language.\n" :parameters
		    [(:label "args ...Type")])]
	   :activeSignature 0 :activeParameter 0)
	  :id 10)
[server-reply] (id:11) Sun Aug  1 09:05:22 2021:
(:jsonrpc "2.0" :result
	  (:contents
	   (:kind "markdown" :value "```go\nfunc math.Abs(x float64) float64\n```\n\n[`math.Abs` on pkg.go.dev](https://pkg.go.dev/math?utm_source=gopls#Abs)\n\nAbs returns the absolute value of x\\.\n\nSpecial cases are\\:\n\n    Abs(±Inf) = +Inf\n    Abs(NaN) = NaN\n")
	   :range
	   (:start
	    (:line 5 :character 12)
	    :end
	    (:line 5 :character 15)))
	  :id 11)
[server-reply] (id:12) Sun Aug  1 09:05:22 2021:
(:jsonrpc "2.0" :result
	  [(:range
	    (:start
	     (:line 5 :character 12)
	     :end
	     (:line 5 :character 15))
	    :kind 1)]
	  :id 12)
[client-request] (id:13) Sun Aug  1 09:05:22 2021:
(:jsonrpc "2.0" :id 13 :method "textDocument/definition" :params
	  (:textDocument
	   (:uri "file:///f:/CASE-eglot/test.go")
	   :position
	   (:line 5 :character 13)))
[server-reply] (id:13) Sun Aug  1 09:05:22 2021:
(:jsonrpc "2.0" :result
	  [(:uri "file:///C:/go/src/math/abs.go" :range
		 (:start
		  (:line 11 :character 5)
		  :end
		  (:line 11 :character 8)))]
	  :id 13)

```
    
#### Backtrace (mandatory, unless no error message seen or heard):

     
```lisp
```
   
#### Minimal configuration (mandatory)
https://github.com/wsw0108/CASE-eglot

     
 ```sh
 # Type this in a shell to start an Emacs with Eglot configured
git clone https://github.com/wsw0108/CASE-eglot CASE-eglot
cd CASE-eglot
emacs -Q -l init.el test.go
 ```
 
 
 
 ```lisp
  ```
 
 

With above configuration, when call `xref-find-definitions` under `math.A|bs`, a new gopls server starts.

Please also refer https://github.com/golang/go/issues/47481

### PR DESCRIPTION
**Pull request by wsw0108**
By downcase 'buffer-file-name' as hash key

### CODE REVIEW

**Comment by joaotavora** [comment]
Thanks, but can you explain how you reached the conclusion that there is a casing problem here? When exactly is one filename with a given casing inserted into the hash table only to be retrieved with a different casing? Give a simple example.

**Comment by wsw0108** [comment]
For feature `eglot-extend-to-xref`, it use var `eglot--servers-by-xrefed-file`. 

From the log attached to this issue, we can see that it's the casing mismatch problem(between lsp server and emacs). So just normalize the key for set/get to/from hash table eglot--servers-by-xrefed-file.

**Comment by joaotavora** [comment]
> From the log attached to this issue, we can see that it's the casing mismatch problem(between lsp server and emacs). So just normalize the key for set/get to/from hash table eglot--servers-by-xrefed-file.

Where can I see this? Can you point it out specifically?

You wrote in that issue:

```
cangd return "file:///C:/Program%20Files%20%28x86%29/Windows%20Kits/10/Include/10.0.19041.0/ucrt/stdio.h"
buffer-file-name is "c:/Program Files (x86)/Windows Kits/10/Include/10.0.19041.0/ucrt/stdio.h"
```

But the difference between the two representations of the same file (presumably) is much more than just casing.

So I must be missing something.

**Comment by wsw0108** [comment]
```
(eglot--uri-to-path "file:///C:/Program%20Files%20%28x86%29/Windows%20Kits/10/Include/10.0.19041.0/ucrt/stdio.h")
"C:/Program Files (x86)/Windows Kits/10/Include/10.0.19041.0/ucrt/stdio.h"
```

When Emacs visit below stdio.h, the `buffer-file-name` will be `"c:/Program Files (x86)/Windows Kits/10/Include/10.0.19041.0/ucrt/stdio.h"`.

And `eglot--xref-make-match` use `eglot--uri-to-path` to extract file from uri.

**Comment by joaotavora** [comment]
Ah, thanks, so it's only the drive letter?

**Comment by wsw0108** [comment]
> Ah, thanks, so it's only the drive letter?

Yes, Emacs just downcase the driver letter under Windows.

**Comment by joaotavora** [comment]
Ok. Then I don't think this is the right solution, as it has the potential
to create new bugs on case sensitive file systems.

**Comment by wsw0108** [comment]
```
(expand-file-name (eglot--uri-to-path "file:///C:/Program%20Files%20%28x86%29/Windows%20Kits/10/Include/10.0.19041.0/ucrt/stdio.h"))
"C:/Program Files (x86)/Windows Kits/10/Include/10.0.19041.0/ucrt/stdio.h"

(expand-file-name "/abc.txt")
"c:/abc.txt"
```

It seems `expand-file-name` handle absolute path specially.

**Comment by wsw0108** [comment]
FYI: https://github.com/emacs-mirror/emacs/blob/d4e3e548f5519e98c2fc842daf73a6acac7faa70/src/fileio.c#L91

**Comment by wsw0108** [comment]
this pr can not fix #715, as gopls does not follow the fs displayed case(ex gopls return C:/go/src, and fs explorer display C:/Go/src.

So I close it.

**Pull request closed without merging**
