### PR TITLE
Support IPC socket connections

### PR DESCRIPTION
**Pull request by snizovtsev**
* eglot.el (eglot--connect): Add support for IPC
* README.md: Add example of IPC socket activation

### CODE REVIEW

**Comment by joaotavora** [comment]
This looks very good, both the Lisp change and the README. 

Just some questions/notes:

1.  Shouldn't the syntax be `(major-mode . (:ipc "/path/to/socket"))` and not the other way around as you suggest?  Are we sure this won't clash with existing syntax?

2. I take it you understand that the interactive `C-u M-x eglot` which lets you specify a server contact from the minibuffer, has no support for this.  I'm fine with that, as long as the existing interface isn't broken.

3. Do you have a copyright assignment to the FSF?

**Comment by snizovtsev** [comment]
1. If we put `:ipc` first it will clash with `(keywordp (car contact)) contact)` rule, which is used to pass-through a raw contact. So I deviate from existing TCP `(stringp integerp)` syntax, treating `:ipc` keyword as a special port number. As far I can see it won't clash with other, otherwise TCP syntax will.
2. Yes, no support for this. And just checked that existing interface continue to work.
3. No, should I get one?

**Comment by joaotavora** [comment]
1. Right.  But I just had a read and what you mean by "raw contact" seems to be the case `(major-mode . (class-name . initargs))` where initargs is the plist that starts with the keyword.  This would seem to indicate that this additional patch:

```diff
diff --git a/eglot.el b/eglot.el
index df921be..6b46849 100644
--- a/eglot.el
+++ b/eglot.el
@@ -720,6 +720,7 @@ be guessed."
                     (funcall guess interactive)
                   guess))
          (class (or (and (consp guess) (symbolp (car guess))
+                         (cl-find-class (car guess))
                          (prog1 (car guess) (setq guess (cdr guess))))
                     'eglot-lsp-server))
          (program (and (listp guess)
```

Could make the order I proposed earlier work.

But that point may be moot altogether.  Why not use  the existing syntax for this, `(MAJOR-MODE . (CLASS . INITARGS))` for this?  In theory, something like this should work:

```lisp
(defclass eglot-ipc-lsp-server (eglot-lsp-server) ())

(cl-defmethod initialize-instance :around ((x eglot-ipc-lsp-server) args)
  (setf (cl-getf args :process)
        (make-network-process :name (cl-getf args :name)
                              :service (cl-getf args :ipc-socket-name)
                              :coding 'utf-8-emacs-unix
                              :noquery t
                              :family 'local))
  (cl-remf args :ipc-socket-name)
  (cl-call-next-method x args))

(add-to-list
 'eglot-server-programs
 `(c++-mode . (eglot-ipc-lsp-server :ipc-socket-name "/tmp/my-clangd-sock")))
```

2. OK no problem, thanks for checking

3. Yes, you do need one.  Please email emacs-devel@gnu.org and ask for a copyright assignment form.  One will be sent offline.  I think your contribution can go in before you finish the process, though.

**Comment by snizovtsev** [comment]
Actually, I've started by the following snippet in my config:
```lisp
(defun eglot-systemd ()
  "Starts systemd-activated LSP server"
  (interactive)
  (let* ((path (f-join (getenv "XDG_RUNTIME_DIR") "clangd"))
         (contact `(:process ,(lambda()
                                (make-network-process
                                 :name "test-unix-sock"
                                 :coding 'utf-8-emacs-unix
                                 :noquery t
                                 :family 'local
                                 :service path))))
         (project '(vc . "~/src/.../")))
    (eglot 'c-mode project eglot-lsp-server contact)))
```

So by term `raw contact` I mean user-defined connection passed through `:process` keyword. Of course `eglot-ipc-lsp-server` is much cleaner than that - i haven't realized it. It solves the `:name` problem.

But how then to combine it with `eglot-rls` or `eglot-eclipse-jdt`? I believe `eglot-lsp-server` descendants implement protocol-level quirks, and they should be orthogonal to connection establishment.

**Comment by joaotavora** [comment]
> But how then to combine it with eglot-rls or eglot-eclipse-jdt? I believe eglot-lsp-server descendants implement protocol-level quirks, and they should be orthogonal to connection establishment.

I think multiple inheritance should have our back here.

**Comment by skangas** [comment]
What is the current status here? I can see that there was some discussion regarding the exact syntax, and also around copyright assignment. I have two questions for @snizovtsev:

1. Did you finish the copyright assignment process?
2. Did you get any further with this PR?

**Pull request closed without merging**
